# Generated by Django 2.0.1 on 2018-10-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("cases", "0002_auto_20181015_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="deficiency_document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deficiency_document",
                to="documents.Document",
            ),
        ),
        migrations.AddField(
            model_name="submissiondocument",
            name="deficient",
            field=models.BooleanField(default=False),
        ),
    ]
