# Generated by Django 2.0.1 on 2018-11-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_auto_20181024_1350"),
    ]

    operations = [
        migrations.AlterIndexTogether(name="caseworkflowstate", index_together={("case", "key")},),
    ]
