# Generated by Django 2.0.1 on 2018-11-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_auto_20181113_1131"),
    ]

    operations = [
        migrations.RemoveField(model_name="submission", name="response_deadline",),
    ]
