# Generated by Django 2.0.1 on 2018-11-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_remove_submission_response_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionstatus", name="draft", field=models.BooleanField(default=False),
        ),
    ]
