# Generated by Django 2.0.1 on 2018-11-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_submissionstatus_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionstatus",
            name="send_confirmation_notification",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
