# Generated by Django 2.0.1 on 2018-11-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_add_submission_status_send_confirmation_notification"),
    ]

    operations = [
        migrations.RemoveField(model_name="submission", name="deficiency_notice",),
    ]
