# Generated by Django 2.0.1 on 2018-11-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_remove_submission_deficiency_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissiontype",
            name="deficiency_template",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="submissiontype",
            name="success_template",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
