# Generated by Django 2.0.1 on 2018-11-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
        ("cases", "0013_auto_20181129_0116"),
    ]

    operations = [
        migrations.AddField(
            model_name="casetype",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workflow.WorkflowTemplate",
            ),
        ),
    ]
