# Generated by Django 2.0.1 on 2018-12-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_auto_20181106_1037"),
        ("cases", "0016_case_initiated_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="case_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="security.CaseRole",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="url",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
