# Generated by Django 2.0.1 on 2018-12-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_auto_20181211_1632"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="time_window",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
