# Generated by Django 2.0.1 on 2018-12-30 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0018_submission_time_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="issued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_issued_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
