# Generated by Django 2.0.1 on 2019-01-10 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0020_auto_20190103_1630"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeGateStatus",
            fields=[
                (
                    "workflow_state",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="cases.CaseWorkflowState",
                    ),
                ),
                ("ack_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ack_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="casetimegate", name="ack_by",),
        migrations.RemoveField(model_name="casetimegate", name="case",),
        migrations.RemoveField(model_name="casetimegate", name="created_by",),
        migrations.RemoveField(model_name="casetimegate", name="modified_by",),
        migrations.RemoveField(model_name="casetimegate", name="time_gate",),
        migrations.RemoveField(model_name="timegate", name="created_by",),
        migrations.RemoveField(model_name="timegate", name="modified_by",),
        migrations.DeleteModel(name="CaseTimeGate",),
        migrations.DeleteModel(name="TimeGate",),
    ]
