# Generated by Django 2.0.1 on 2019-01-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_timegate_action_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissiontype",
            name="time_window_key",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
