# Generated by Django 2.0.1 on 2019-01-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0022_add_submission_type_time_window_key"),
    ]

    operations = [
        migrations.RemoveField(model_name="submission", name="deficiency_document",),
    ]
