# Generated by Django 2.0.1 on 2019-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0023_remove_submission_deficiency_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissiontype",
            name="notify_template",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
