# Generated by Django 2.0.1 on 2019-02-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0024_submissiontype_notify_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={
                "permissions": (
                    ("create_ex_oficio", "Can create an ex-oficio case"),
                    (
                        "complete_decision_tasks",
                        "Can complete decision tasks like initiation decision, final determination etc.",
                    ),
                    ("can_assign_team", "Can assign manager and team to the case"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "permissions": (
                    ("send_deficiency_notice", "Can send deficiency notices"),
                    ("publish_public", "Can issue to the public case record"),
                    ("publish_public_tasklist", "Can complete the public publish tasklist"),
                    (
                        "publish_non_conf_interested_parties",
                        "Can publish the non confidentials of interested parties",
                    ),
                    ("close_case_tasks", "Can complete close case tasks"),
                    ("case_admin", "Can access case admin panel"),
                )
            },
        ),
    ]
