# Generated by Django 2.0.1 on 2019-02-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0026_auto_20190221_1358"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={
                "permissions": (
                    ("create_ex_oficio", "Can create an ex-oficio case"),
                    (
                        "complete_decision_tasks",
                        "Can complete decision tasks like initiation decision, final determination etc.",
                    ),
                    ("can_assign_team", "Can assign manager and team to the case"),
                    (
                        "issue_submission_requests",
                        "Can issue submission requests (questionnaires, visit report etc.)",
                    ),
                    ("workflow_editor", "Can access the workflow editor"),
                )
            },
        ),
    ]
