# Generated by Django 2.0.1 on 2019-02-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0027_auto_20190221_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseworkflowstate",
            name="key",
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
