# Generated by Django 2.0.1 on 2019-02-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0028_add_caseworkflowstate_key_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseworkflow",
            name="case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow",
                to="cases.Case",
            ),
        ),
    ]
