# Generated by Django 2.0.1 on 2019-03-22 10:10

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0030_submissiontype_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="deficiency_notice_params",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="received_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_received_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissiondocument",
            name="sufficient",
            field=models.BooleanField(default=False),
        ),
    ]
