# Generated by Django 2.0.13 on 2019-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0033_casetype_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="casetype", name="internal", field=models.BooleanField(default=False),
        ),
    ]
