# Generated by Django 2.0.13 on 2019-08-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0037_submissionstatus_review_ok"),
    ]

    operations = [
        migrations.RemoveField(model_name="documenttemplate", name="created_by",),
        migrations.RemoveField(model_name="documenttemplate", name="document",),
        migrations.RemoveField(model_name="documenttemplate", name="modified_by",),
        migrations.RemoveField(model_name="documenttemplate", name="submission",),
        migrations.DeleteModel(name="DocumentTemplate",),
    ]
