# Generated by Django 2.2.5 on 2019-12-03 16:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0040_submission_organisation_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="casetype",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
