# Generated by Django 2.2.5 on 2019-12-03 17:14

import audit.mixins
import dirtyfields.dirtyfields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0041_casetype_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="MilestoneType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("key", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CaseMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("history", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="cases.Case"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casemilestone_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casemilestone_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cases.MilestoneType"
                    ),
                ),
            ],
            options={"unique_together": {("case", "type")},},
            bases=(
                models.Model,
                dirtyfields.dirtyfields.DirtyFieldsMixin,
                audit.mixins.AuditableMixin,
            ),
        ),
    ]
