# Generated by Django 2.2.5 on 2019-12-05 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0042_casemilestone_milestonetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="cases.Case"
            ),
        ),
    ]
