# Generated by Django 2.2.5 on 2019-12-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0044_auto_20191206_1016"),
    ]

    operations = [
        migrations.DeleteModel(name="CaseMilestone",),
        migrations.DeleteModel(name="MilestoneType",),
    ]
