# Generated by Django 2.2.5 on 2020-01-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0046_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice", name="published_at", field=models.DateField(blank=True, null=True),
        ),
    ]
