# Generated by Django 2.2.5 on 2020-01-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0047_notice_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="case_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cases.CaseType",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="review_case",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="cases.Case"
            ),
        ),
    ]
