# Generated by Django 2.2.5 on 2020-03-20 08:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0049_auto_20200120_1341"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissiontype",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
