# Generated by Django 2.2.13 on 2020-11-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0050_submissiontype_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="case_email",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
