# Generated by Django 2.2.13 on 2021-02-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0050_submissiontype_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='extra_info_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
