# Generated by Django 2.2.13 on 2021-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0050_submissiontype_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionstatus',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
