# Generated by Django 2.2.13 on 2021-02-08 17:37

from django.db import migrations

submissiontype_values = {
    "Application": {
        "key": "application",
        "direction": 1,
        "deficiency_template": "NOTIFY_APPLICATION_INSUFFICIENT",
        "success_template": "NOTIFY_APPLICATION_SUCCESSFUL",
    },
    "Questionnaire": {"key": "questionnaire", "direction": 2},
    "General": {
        "key": "adhoc",
        "direction": 1,
        "notify_template": "NOTIFY_AD_HOC_EMAIL",
        "time_window_key": "GENERAL_SUBMISSION_TIMER",
    },
    "Ex Officio Application": {"key": "application", "direction": 0},
    "Notice of Initiation": {"key": "public", "direction": 0, "order": 1},
    "Pre-Sampling Questionnaire": {"key": "questionnaire", "direction": 2},
    "Registration of Interest": {
        "key": "interest",
        "direction": 1,
        "time_window_key": "REGISTRATION_OF_INTEREST_TIMER",
        "meta": {"bundle_files_limit": "case"},
    },
    "The Statement of Essential Facts": {"key": "public", "direction": 0, "order": 30},
    "Response to the Statement of Essential Facts": {
        "key": "adhoc",
        "direction": 1,
        "time_window_key": "PROV_FACTS_HEARINGS_RESPONSE_TIMER",
    },
    "Final determination": {"key": "public", "direction": 0, "order": 35},
    "Provisional determination": {"key": "public", "direction": 0, "order": 25},
    "Visit Report": {
        "key": "visitreport",
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    "Application report": {
        "key": "questionnaire",
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    "Hearing notification": {
        "key": "questionnaire",
        "direction": 2,
        "notify_template": "NOTIFY_HEARING_ARRANGEMENTS",
    },
    "Reconsideration report": {"key": "public", "direction": 0, "order": 40},
    "Response to the Provisional Determination": {
        "key": "adhoc",
        "direction": 1,
        "time_window_key": "PROV_PUBLISH_PUBLISHED",
    },
    "Hearing request": {
        "key": "adhoc",
        "direction": 1,
        "time_window_key": "PROV_FACTS_HEARINGS_TIMER",
    },
    "Response to the Full Determination": {"key": "adhoc", "direction": 1},
    "Reconsideration request": {
        "key": "adhoc",
        "direction": 1,
        "time_window_key": "RECON_REQUEST_SUBMISSION_TIMER",
    },
    "Ad-hoc": {"key": "questionnaire", "direction": 2, "notify_template": "NOTIFY_AD_HOC_EMAIL"},
    "Invite 3rd party": {"key": "invite", "direction": 1},
    "Statement of intended final determination": {"key": "public", "direction": 0, "order": 30},
    "Authentication report": {
        "key": "questionnaire",
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    "Response to the statement of intended final determination": {
        "key": "adhoc",
        "direction": 1,
        "time_window_key": "RESPOND_SOIFD_SUBMISSION_TIMER",
    },
    "Request appeal": {
        "key": "adhoc",
        "direction": 1,
        "time_window_key": "REQUEST_APPEAL_SUBMISSION_TIMER",
    },
    "Additional User Request": {"key": "assign", "direction": 1},
    "General publication - Extra": {
        "key": "public",
        "direction": 0,
        "order": 29,
        "extra_info_required": True,
    },
    "General publication - Application": {"key": "public", "direction": 0, "order": 3,},
    "General publication - Note of meeting": {"key": "public", "direction": 0, "order": 5,},
    "General publication - Notice of extension": {"key": "public", "direction": 0, "order": 7,},
    "General publication - Notice of proposed sample": {
        "key": "public",
        "direction": 0,
        "order": 9,
    },
    "General publication - Case timeline": {"key": "public", "direction": 0, "order": 11,},
    "General publication - Submission (from an interested party)": {
        "key": "public",
        "direction": 0,
        "order": 15,
    },
    "General publication - Pre-sampling questionnaire": {
        "key": "public",
        "direction": 0,
        "order": 17,
    },
    "General publication - Questionnaire": {"key": "public", "direction": 0, "order": 19,},
    "General publication - Verification report": {"key": "public", "direction": 0, "order": 21,},
    "General publication - Final reports": {"key": "public", "direction": 0, "order": 23,},
    "General publication - Termination reports": {"key": "public", "direction": 0, "order": 27,},
}

type_requires = {
    "Response to the Statement of Essential Facts": "The Statement of Essential Facts",
    "Hearing notification": "Hearing request",
    "Reconsideration report": "Reconsideration request",
    "Response to the Provisional Determination": "Provisional determination",
    "Response to the Full Determination": "Hearing request",
}


def create_update_submissiontype(apps, schema_editor):
    SubmissionType = apps.get_model('cases', 'SubmissionType')
    for key, values in submissiontype_values.items():
        SubmissionType.objects.update_or_create(name=key, defaults=values)

    for key, value in type_requires.items():
        obj_requiring = SubmissionType.objects.get(name= key)
        obj_required = SubmissionType.objects.get(name= value)
        obj_requiring.requires = obj_required
        obj_requiring.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0051_submissiontype_extra_field"),
    ]

    operations = [
        migrations.RunPython(create_update_submissiontype),
    ]
