# Generated by Django 2.2.13 on 2021-02-17 14:41
import logging

from django.db import migrations, IntegrityError

import cases.constants as constants

logger = logging.getLogger(__name__)


PUBLIC_KEY = "public"
AD_HOC_KEY = "adhoc"
QUESTIONNAIRE_KEY = "questionnaire"


submission_type_values = {
    constants.SUBMISSION_TYPE_APPLICATION: {
        "name": "Application",
        "key": "application",
        "direction": 1,
        "deficiency_template": "NOTIFY_APPLICATION_INSUFFICIENT",
        "success_template": "NOTIFY_APPLICATION_SUCCESSFUL",
    },
    constants.SUBMISSION_TYPE_QUESTIONNAIRE: {
        "name": "Questionnaire",
        "key": QUESTIONNAIRE_KEY,
        "direction": 2,
    },
    constants.SUBMISSION_TYPE_GENERAL: {
        "name": "General",
        "key": AD_HOC_KEY,
        "direction": 1,
        "notify_template": "NOTIFY_AD_HOC_EMAIL",
        "time_window_key": "GENERAL_SUBMISSION_TIMER",
    },
    constants.SUBMISSION_TYPE_EX_OFFICIO: {
        "name": "Ex Officio Application",
        "key": "application",
        "direction": 0,
    },
    constants.SUBMISSION_TYPE_NOTICE_OF_INITIATION: {
        "name": "Notice of Initiation",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 1,
    },
    constants.SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE: {
        "name": "Pre-Sampling Questionnaire",
        "key": QUESTIONNAIRE_KEY,
        "direction": 2,
    },
    constants.SUBMISSION_TYPE_REGISTER_INTEREST: {
        "name": "Registration of Interest",
        "key": "interest",
        "direction": 1,
        "time_window_key": "REGISTRATION_OF_INTEREST_TIMER",
        "meta": {"bundle_files_limit": "case"},
    },
    constants.SUBMISSION_TYPE_STATEMENT_OF_ESSENTIAL_FACTS: {
        "name": "The Statement of Essential Facts",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 30,
    },
    constants.SUBMISSION_TYPE_STATEMENT_OF_ESSENTIAL_FACTS_RESPONSE: {
        "name": "Response to the Statement of Essential Facts",
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_FACTS_HEARINGS_RESPONSE_TIMER",
    },
    constants.SUBMISSION_TYPE_FINAL_DETERMINATION: {
        "name": "Final determination",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 35,
    },
    constants.SUBMISSION_TYPE_PROVISIONAL_DETERMINATION: {
        "name": "Provisional determination",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 32,
    },
    constants.SUBMISSION_TYPE_VISIT_REPORT: {
        "name": "Visit Report",
        "key": "visitreport",
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    constants.SUBMISSION_TYPE_APPLICATION_REPORT: {
        "name": "Application report",
        "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    constants.SUBMISSION_TYPE_HEARING_NOTIFICATION: {
        "name": "Hearing notification",
        "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_HEARING_ARRANGEMENTS",
    },
    constants.SUBMISSION_TYPE_RECONSIDERATION_REPORT: {
        "name": "Reconsideration report",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 40,
    },
    constants.SUBMISSION_TYPE_PROVISIONAL_DETERMINATION_RESPONSE: {
        "name": "Response to the Provisional Determination",
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_PUBLISH_PUBLISHED",
    },
    constants.SUBMISSION_TYPE_HEARING_REQUEST: {
        "name": "Hearing request",
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_FACTS_HEARINGS_TIMER",
    },
    constants.SUBMISSION_TYPE_FULL_DETERMINATION_RESPONSE: {
        "name": "Response to the Full Determination",
        "key": AD_HOC_KEY,
        "direction": 1,
    },
    constants.SUBMISSION_TYPE_RECONSIDERATION_REQUEST: {
        "name": "Reconsideration request",
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "RECON_REQUEST_SUBMISSION_TIMER",
    },
    constants.SUBMISSION_TYPE_AD_HOC: {
        "name": "Ad-hoc",
        "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_AD_HOC_EMAIL",
    },
    constants.SUBMISSION_TYPE_INVITE_3RD_PARTY: {
        "name": "Invite 3rd party",
        "key": "invite",
        "direction": 1,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION: {
        "name": "General publication - Other",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 29,
    },
    constants.SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION: {
        "name": "Statement of intended final determination",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 30,
    },
    constants.SUBMISSION_TYPE_AUTHENTICATION_REPORT: {
        "name": "Authentication report",
        "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    constants.SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION_RESPONSE: {
        "name": "Response to the statement of intended final determination",
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "RESPOND_SOIFD_SUBMISSION_TIMER",
    },
    constants.SUBMISSION_TYPE_REQUEST_APPEAL: {
        "name": "Request appeal",
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "REQUEST_APPEAL_SUBMISSION_TIMER",
    },
    constants.SUBMISSION_TYPE_ASSIGN_TO_CASE: {
        "name": "Additional User Request",
        "key": "assign",
        "direction": 1,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION_APPLICATION: {
        "name": "General publication - Application",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 4,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTE_OF_MEETING: {
        "name": "General publication - Note of meeting",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 5,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_EXTENSION: {
        "name": "General publication - Notice of extension",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 7,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_PROPOSED_SAMPLE: {
        "name": "General publication - Notice of proposed sample",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 9,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION_CASE_TIMELINE: {
        "name": "General publication - Case timeline",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 11,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION_SUBMISSION_FROM_AN_INTERESTED_PARTY: {
        "name": "General publication - Submission (from an interested party)",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 15,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION_PRE_SAMPLING_QUESTIONNAIRE: {
        "name": "General publication - Pre-sampling questionnaire",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 17,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION_QUESTIONNAIRE: {
        "name": "General publication - Questionnaire",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 19,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION_VERIFICATION_REPORT: {
        "name": "General publication - Verification report",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 21,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION_FINAL_REPORTS: {
        "name": "General publication - Final reports",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 23,
    },
    constants.SUBMISSION_TYPE_GENERAL_PUBLICATION_TERMINATION_REPORTS: {
        "name": "General publication - Termination reports",
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 27,
    },
}


type_requires = {
    "Response to the Statement of Essential Facts": "The Statement of Essential Facts",
    "Hearing notification": "Hearing request",
    "Reconsideration report": "Reconsideration request",
    "Response to the Provisional Determination": "Provisional determination",
    "Response to the Full Determination": "Hearing request",
}


def create_update_submission_types(apps, schema_editor):  # noqa
    """Create or update submission types.

    Formerly submission type initial data was loaded using json fixtures.
    This migration takes a preferred approach to load those data using
    `submission_type_values` defined in this module.
    """
    submission_type_class = apps.get_model("cases", "SubmissionType")
    for key, values in submission_type_values.items():
        try:
            submission_type_class.objects.update_or_create(id=key, defaults=values)
        except IntegrityError as e:
            logger.critical(f"Migration error! You may need to manually address this issue: {e}")

    for key, value in type_requires.items():
        submission_type = submission_type_class.objects.get(name=key)
        if not submission_type:
            logger.warning(
                f"No submission type found with name '{key}', "
                f"you may need to manually address this issue"
            )
            continue
        required_submission_type = submission_type_class.objects.get(name=value)
        if not required_submission_type:
            logger.warning(
                f"No required submission type found with name '{key}', "
                f"you may need to manually address this issue"
            )
            continue
        submission_type.requires = required_submission_type
        submission_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0051_auto_20210217_1440"),
    ]

    operations = [
        migrations.RunPython(create_update_submission_types),
    ]
