# Generated by Django 2.2.13 on 2021-02-09 16:32

from django.db import migrations

from cases.constants import (
    SUBMISSION_TYPE_APPLICATION,
    SUBMISSION_TYPE_QUESTIONNAIRE,
    SUBMISSION_TYPE_GENERAL,
    SUBMISSION_TYPE_EX_OFFICIO,
    SUBMISSION_TYPE_NOTICE_OF_INITIATION,
    SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE,
    SUBMISSION_TYPE_REGISTER_INTEREST,
    SUBMISSION_TYPE_STATEMENT_OF_ESSENTIAL_FACTS,
    SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_ESSENTIAL_FACTS,
    SUBMISSION_TYPE_FINAL_DETERMINATION,
    SUBMISSION_TYPE_PROVISIONAL_DETERMINATION,
    SUBMISSION_TYPE_VISIT_REPORT,
    SUBMISSION_TYPE_APPLICATION_REPORT,
    SUBMISSION_TYPE_HEARING_NOTIFICATION,
    SUBMISSION_TYPE_RECONSIDERATION_REPORT,
    SUBMISSION_TYPE_RESPONSE_TO_THE_PROVISIONAL_DETERMINATION,
    SUBMISSION_TYPE_HEARING_REQUEST,
    SUBMISSION_TYPE_RESPONSE_TO_THE_FULL_DETERMINATION,
    SUBMISSION_TYPE_RECONSIDERATION_REQUEST,
    SUBMISSION_TYPE_AD_HOC,
    SUBMISSION_TYPE_INVITE_3RD_PARTY,
    SUBMISSION_TYPE_GENERAL_PUBLICATION,
    SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
    SUBMISSION_TYPE_AUTHENTICATION_REPORT,
    SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
    SUBMISSION_TYPE_REQUEST_APPEAL,
    SUBMISSION_TYPE_ASSIGN_TO_CASE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_APPLICATION,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTE_OF_MEETING,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_EXTENSION,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_PROPOSED_SAMPLE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_CASE_TIMELINE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_SUBMISSION_FROM_AN_INTERESTED_PARTY,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_PRE_SAMPLING_QUESTIONNAIRE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_QUESTIONNAIRE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_VERIFICATION_REPORT,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_FINAL_REPORTS,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_TERMINATION_REPORTS,
)

PUBLIC_KEY = "public"
AD_HOC_KEY= "adhoc"
QUESTIONNAIRE_KEY= "questionnaire"

submissiontype_values = {
    "Application": {
        "id": SUBMISSION_TYPE_APPLICATION,
        "key": "application",
        "direction": 1,
        "deficiency_template": "NOTIFY_APPLICATION_INSUFFICIENT",
        "success_template": "NOTIFY_APPLICATION_SUCCESSFUL",
    },
    "Questionnaire": {"id": SUBMISSION_TYPE_QUESTIONNAIRE, "key": QUESTIONNAIRE_KEY, "direction": 2},
    "General": {
        "id": SUBMISSION_TYPE_GENERAL,
        "key": AD_HOC_KEY,
        "direction": 1,
        "notify_template": "NOTIFY_AD_HOC_EMAIL",
        "time_window_key": "GENERAL_SUBMISSION_TIMER",
    },
    "Ex Officio Application": {"id": SUBMISSION_TYPE_EX_OFFICIO, "key": "application", "direction": 0},
    "Notice of Initiation": {"id": SUBMISSION_TYPE_NOTICE_OF_INITIATION, "key": PUBLIC_KEY, "direction": 0, "order": 1},
    "Pre-Sampling Questionnaire": {"id": SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE, "key": QUESTIONNAIRE_KEY, "direction": 2},
    "Registration of Interest": {
        "id": SUBMISSION_TYPE_REGISTER_INTEREST,
        "key": "interest",
        "direction": 1,
        "time_window_key": "REGISTRATION_OF_INTEREST_TIMER",
        "meta": {"bundle_files_limit": "case"},
    },
    "The Statement of Essential Facts": {"id": SUBMISSION_TYPE_STATEMENT_OF_ESSENTIAL_FACTS, "key": PUBLIC_KEY, "direction": 0, "order": 30},
    "Response to the Statement of Essential Facts": {
        "id": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_ESSENTIAL_FACTS, "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_FACTS_HEARINGS_RESPONSE_TIMER",
    },
    "Final determination": {"id": SUBMISSION_TYPE_FINAL_DETERMINATION, "key": PUBLIC_KEY, "direction": 0, "order": 35},
    "Provisional determination": {"id": SUBMISSION_TYPE_PROVISIONAL_DETERMINATION, "key": PUBLIC_KEY, "direction": 0, "order": 32},
    "Visit Report": {
        "id": SUBMISSION_TYPE_VISIT_REPORT, "key": "visitreport",
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    "Application report": {
        "id": SUBMISSION_TYPE_APPLICATION_REPORT, "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    "Hearing notification": {
        "id": SUBMISSION_TYPE_HEARING_NOTIFICATION, "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_HEARING_ARRANGEMENTS",
    },
    "Reconsideration report": {"id": SUBMISSION_TYPE_RECONSIDERATION_REPORT, "key": PUBLIC_KEY, "direction": 0, "order": 40},
    "Response to the Provisional Determination": {
        "id": SUBMISSION_TYPE_RESPONSE_TO_THE_PROVISIONAL_DETERMINATION, "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_PUBLISH_PUBLISHED",
    },
    "Hearing request": {
        "id": SUBMISSION_TYPE_HEARING_REQUEST, "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_FACTS_HEARINGS_TIMER",
    },
    "Response to the Full Determination": {"id": SUBMISSION_TYPE_RESPONSE_TO_THE_FULL_DETERMINATION, "key": AD_HOC_KEY, "direction": 1},
    "Reconsideration request": {
        "id": SUBMISSION_TYPE_RECONSIDERATION_REQUEST, "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "RECON_REQUEST_SUBMISSION_TIMER",
    },
    "Ad-hoc": {"id": SUBMISSION_TYPE_AD_HOC, "key": QUESTIONNAIRE_KEY, "direction": 2, "notify_template": "NOTIFY_AD_HOC_EMAIL"},
    "Invite 3rd party": {"id": SUBMISSION_TYPE_INVITE_3RD_PARTY, "key": "invite", "direction": 1},
    "General publication - other": {
        "id": SUBMISSION_TYPE_GENERAL_PUBLICATION, "key": PUBLIC_KEY,
        "direction": 0,
        "order": 29,
        "extra_info_required": True,
    },
    "Statement of intended final determination": {"id": SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION, "key": PUBLIC_KEY, "direction": 0, "order": 30},
    "Authentication report": {
        "id": SUBMISSION_TYPE_AUTHENTICATION_REPORT, "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    "Response to the statement of intended final determination": {
        "id": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION, "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "RESPOND_SOIFD_SUBMISSION_TIMER",
    },
    "Request appeal": {
        "id": SUBMISSION_TYPE_REQUEST_APPEAL, "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "REQUEST_APPEAL_SUBMISSION_TIMER",
    },
    "Additional User Request": {"id": SUBMISSION_TYPE_ASSIGN_TO_CASE, "key": "assign", "direction": 1},
    "General publication - Application": {"id": SUBMISSION_TYPE_GENERAL_PUBLICATION_APPLICATION, "key": PUBLIC_KEY, "direction": 0, "order": 4,},
    "General publication - Note of meeting": {"id": SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTE_OF_MEETING, "key": PUBLIC_KEY, "direction": 0, "order": 5,},
    "General publication - Notice of extension": {"id": SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_EXTENSION, "key": PUBLIC_KEY, "direction": 0, "order": 7,},
    "General publication - Notice of proposed sample": {
        "id": SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_PROPOSED_SAMPLE, "key": PUBLIC_KEY,
        "direction": 0,
        "order": 9,
    },
    "General publication - Case timeline": {"id": SUBMISSION_TYPE_GENERAL_PUBLICATION_CASE_TIMELINE, "key": PUBLIC_KEY, "direction": 0, "order": 11,},
    "General publication - Submission (from an interested party)": {
        "id": SUBMISSION_TYPE_GENERAL_PUBLICATION_SUBMISSION_FROM_AN_INTERESTED_PARTY, "key": PUBLIC_KEY,
        "direction": 0,
        "order": 15,
    },
    "General publication - Pre-sampling questionnaire": {
        "id": SUBMISSION_TYPE_GENERAL_PUBLICATION_PRE_SAMPLING_QUESTIONNAIRE, "key": PUBLIC_KEY,
        "direction": 0,
        "order": 17,
    },
    "General publication - Questionnaire": {"id": SUBMISSION_TYPE_GENERAL_PUBLICATION_QUESTIONNAIRE, "key": PUBLIC_KEY, "direction": 0, "order": 19,},
    "General publication - Verification report": {"id": SUBMISSION_TYPE_GENERAL_PUBLICATION_VERIFICATION_REPORT, "key": PUBLIC_KEY, "direction": 0, "order": 21,},
    "General publication - Final reports": {"id": SUBMISSION_TYPE_GENERAL_PUBLICATION_FINAL_REPORTS, "key": PUBLIC_KEY, "direction": 0, "order": 23,},
    "General publication - Termination reports": {"id": SUBMISSION_TYPE_GENERAL_PUBLICATION_TERMINATION_REPORTS, "key": PUBLIC_KEY, "direction": 0, "order": 27,},
}

type_requires = {
    "Response to the Statement of Essential Facts": "The Statement of Essential Facts",
    "Hearing notification": "Hearing request",
    "Reconsideration report": "Reconsideration request",
    "Response to the Provisional Determination": "Provisional determination",
    "Response to the Full Determination": "Hearing request",
}


def create_update_submissiontype(apps, schema_editor):
    SubmissionType = apps.get_model('cases', 'SubmissionType')
    for key, values in submissiontype_values.items():
        SubmissionType.objects.update_or_create(name=key, defaults=values)

    for key, value in type_requires.items():
        obj_requiring = SubmissionType.objects.get(name= key)
        obj_required = SubmissionType.objects.get(name= value)
        obj_requiring.requires = obj_required
        obj_requiring.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0051_auto_20210209_1631"),
    ]

    operations = [
        migrations.RunPython(create_update_submissiontype),
    ]
