# Generated by Django 2.2.13 on 2021-02-08 17:37

from django.db import migrations

from cases.constants import (
    SUBMISSION_TYPE_APPLICATION_NAME,
    SUBMISSION_TYPE_EX_OFFICIO_NAME,
    SUBMISSION_TYPE_NOTICE_OF_INITIATION_NAME,
    SUBMISSION_TYPE_REGISTER_INTEREST_NAME,
    SUBMISSION_TYPE_INVITE_3RD_PARTY_NAME,
    SUBMISSION_TYPE_HEARING_REQUEST_NAME ,
    SUBMISSION_TYPE_STATEMENT_OF_ESSENTIAL_FACTS_NAME,
    SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION_NAME,
    SUBMISSION_TYPE_FINAL_DETERMINATION_NAME,
    SUBMISSION_TYPE_PROVISIONAL_DETERMINATION_NAME,
)

PUBLIC_KEY = "public"
AD_HOC_KEY= "adhoc"
QUESTIONNAIRE_KEY= "questionnaire"

submissiontype_values = {
    SUBMISSION_TYPE_APPLICATION_NAME: {
        "key": "application",
        "direction": 1,
        "deficiency_template": "NOTIFY_APPLICATION_INSUFFICIENT",
        "success_template": "NOTIFY_APPLICATION_SUCCESSFUL",
    },
    "Questionnaire": {"key": QUESTIONNAIRE_KEY, "direction": 2},
    "General": {
        "key": AD_HOC_KEY,
        "direction": 1,
        "notify_template": "NOTIFY_AD_HOC_EMAIL",
        "time_window_key": "GENERAL_SUBMISSION_TIMER",
    },
    SUBMISSION_TYPE_EX_OFFICIO_NAME: {"key": "application", "direction": 0},
    SUBMISSION_TYPE_NOTICE_OF_INITIATION_NAME: {"key": PUBLIC_KEY, "direction": 0, "order": 1},
    "Pre-Sampling Questionnaire": {"key": QUESTIONNAIRE_KEY, "direction": 2},
    SUBMISSION_TYPE_REGISTER_INTEREST_NAME: {
        "key": "interest",
        "direction": 1,
        "time_window_key": "REGISTRATION_OF_INTEREST_TIMER",
        "meta": {"bundle_files_limit": "case"},
    },
    SUBMISSION_TYPE_STATEMENT_OF_ESSENTIAL_FACTS_NAME: {"key": PUBLIC_KEY, "direction": 0, "order": 30},
    "Response to the Statement of Essential Facts": {
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_FACTS_HEARINGS_RESPONSE_TIMER",
    },
    SUBMISSION_TYPE_FINAL_DETERMINATION_NAME: {"key": PUBLIC_KEY, "direction": 0, "order": 35},
    SUBMISSION_TYPE_PROVISIONAL_DETERMINATION_NAME: {"key": PUBLIC_KEY, "direction": 0, "order": 25},
    "Visit Report": {
        "key": "visitreport",
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    "Application report": {
        "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    "Hearing notification": {
        "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_HEARING_ARRANGEMENTS",
    },
    "Reconsideration report": {"key": PUBLIC_KEY, "direction": 0, "order": 40},
    "Response to the Provisional Determination": {
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_PUBLISH_PUBLISHED",
    },
    SUBMISSION_TYPE_HEARING_REQUEST_NAME: {
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_FACTS_HEARINGS_TIMER",
    },
    "Response to the Full Determination": {"key": AD_HOC_KEY, "direction": 1},
    "Reconsideration request": {
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "RECON_REQUEST_SUBMISSION_TIMER",
    },
    "Ad-hoc": {"key": QUESTIONNAIRE_KEY, "direction": 2, "notify_template": "NOTIFY_AD_HOC_EMAIL"},
    SUBMISSION_TYPE_INVITE_3RD_PARTY_NAME: {"key": "invite", "direction": 1},
    SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION_NAME: {"key": PUBLIC_KEY, "direction": 0, "order": 30},
    "Authentication report": {
        "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    "Response to the statement of intended final determination": {
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "RESPOND_SOIFD_SUBMISSION_TIMER",
    },
    "Request appeal": {
        "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "REQUEST_APPEAL_SUBMISSION_TIMER",
    },
    "Additional User Request": {"key": "assign", "direction": 1},
    "General publication - Extra": {
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 29,
        "extra_info_required": True,
    },
    "General publication - Application": {"key": PUBLIC_KEY, "direction": 0, "order": 3,},
    "General publication - Note of meeting": {"key": PUBLIC_KEY, "direction": 0, "order": 5,},
    "General publication - Notice of extension": {"key": PUBLIC_KEY, "direction": 0, "order": 7,},
    "General publication - Notice of proposed sample": {
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 9,
    },
    "General publication - Case timeline": {"key": PUBLIC_KEY, "direction": 0, "order": 11,},
    "General publication - Submission (from an interested party)": {
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 15,
    },
    "General publication - Pre-sampling questionnaire": {
        "key": PUBLIC_KEY,
        "direction": 0,
        "order": 17,
    },
    "General publication - Questionnaire": {"key": PUBLIC_KEY, "direction": 0, "order": 19,},
    "General publication - Verification report": {"key": PUBLIC_KEY, "direction": 0, "order": 21,},
    "General publication - Final reports": {"key": PUBLIC_KEY, "direction": 0, "order": 23,},
    "General publication - Termination reports": {"key": PUBLIC_KEY, "direction": 0, "order": 27,},
}

type_requires = {
    "Response to the Statement of Essential Facts": "The Statement of Essential Facts",
    "Hearing notification": "Hearing request",
    "Reconsideration report": "Reconsideration request",
    "Response to the Provisional Determination": "Provisional determination",
    "Response to the Full Determination": "Hearing request",
}


def create_update_submissiontype(apps, schema_editor):
    SubmissionType = apps.get_model('cases', 'SubmissionType')
    for key, values in submissiontype_values.items():
        SubmissionType.objects.update_or_create(name=key, defaults=values)

    for key, value in type_requires.items():
        obj_requiring = SubmissionType.objects.get(name= key)
        obj_required = SubmissionType.objects.get(name= value)
        obj_requiring.requires = obj_required
        obj_requiring.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0051_submissiontype_extra_field"),
    ]

    operations = [
        migrations.RunPython(create_update_submissiontype),
    ]
