# Generated by Django 2.2.13 on 2021-02-17 14:41

from django.db import migrations


from cases.constants import (
    SUBMISSION_TYPE_APPLICATION,
    SUBMISSION_TYPE_QUESTIONNAIRE,
    SUBMISSION_TYPE_GENERAL,
    SUBMISSION_TYPE_EX_OFFICIO,
    SUBMISSION_TYPE_NOTICE_OF_INITIATION,
    SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE,
    SUBMISSION_TYPE_REGISTER_INTEREST,
    SUBMISSION_TYPE_STATEMENT_OF_ESSENTIAL_FACTS,
    SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_ESSENTIAL_FACTS,
    SUBMISSION_TYPE_FINAL_DETERMINATION,
    SUBMISSION_TYPE_PROVISIONAL_DETERMINATION,
    SUBMISSION_TYPE_VISIT_REPORT,
    SUBMISSION_TYPE_APPLICATION_REPORT,
    SUBMISSION_TYPE_HEARING_NOTIFICATION,
    SUBMISSION_TYPE_RECONSIDERATION_REPORT,
    SUBMISSION_TYPE_RESPONSE_TO_THE_PROVISIONAL_DETERMINATION,
    SUBMISSION_TYPE_HEARING_REQUEST,
    SUBMISSION_TYPE_RESPONSE_TO_THE_FULL_DETERMINATION,
    SUBMISSION_TYPE_RECONSIDERATION_REQUEST,
    SUBMISSION_TYPE_AD_HOC,
    SUBMISSION_TYPE_INVITE_3RD_PARTY,
    SUBMISSION_TYPE_GENERAL_PUBLICATION,
    SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
    SUBMISSION_TYPE_AUTHENTICATION_REPORT,
    SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
    SUBMISSION_TYPE_REQUEST_APPEAL,
    SUBMISSION_TYPE_ASSIGN_TO_CASE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_APPLICATION,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTE_OF_MEETING,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_EXTENSION,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_PROPOSED_SAMPLE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_CASE_TIMELINE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_SUBMISSION_FROM_AN_INTERESTED_PARTY,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_PRE_SAMPLING_QUESTIONNAIRE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_QUESTIONNAIRE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_VERIFICATION_REPORT,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_FINAL_REPORTS,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_TERMINATION_REPORTS,
)

PUBLIC_KEY = "public"
AD_HOC_KEY= "adhoc"
QUESTIONNAIRE_KEY= "questionnaire"

submissiontype_values = {
    SUBMISSION_TYPE_APPLICATION: {
        "name": "Application",
        "key": "application",
        "direction": 1,
        "deficiency_template": "NOTIFY_APPLICATION_INSUFFICIENT",
        "success_template": "NOTIFY_APPLICATION_SUCCESSFUL",
    },
    SUBMISSION_TYPE_QUESTIONNAIRE: {"name": "Questionnaire", "key": QUESTIONNAIRE_KEY, "direction": 2},
    SUBMISSION_TYPE_GENERAL: {
        "name": "General",
        "key": AD_HOC_KEY,
        "direction": 1,
        "notify_template": "NOTIFY_AD_HOC_EMAIL",
        "time_window_key": "GENERAL_SUBMISSION_TIMER",
    },
    SUBMISSION_TYPE_EX_OFFICIO: {"name": "Ex Officio Application", "key": "application", "direction": 0},
    SUBMISSION_TYPE_NOTICE_OF_INITIATION: {"name": "Notice of Initiation", "key": PUBLIC_KEY, "direction": 0, "order": 1},
    SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE: {"name": "Pre-Sampling Questionnaire", "key": QUESTIONNAIRE_KEY, "direction": 2},
    SUBMISSION_TYPE_REGISTER_INTEREST: {
        "name": "Registration of Interest",
        "key": "interest",
        "direction": 1,
        "time_window_key": "REGISTRATION_OF_INTEREST_TIMER",
        "meta": {"bundle_files_limit": "case"},
    },
    SUBMISSION_TYPE_STATEMENT_OF_ESSENTIAL_FACTS: {"name": "The Statement of Essential Facts", "key": PUBLIC_KEY, "direction": 0, "order": 30},
    SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_ESSENTIAL_FACTS: {
        "name": "Response to the Statement of Essential Facts", "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_FACTS_HEARINGS_RESPONSE_TIMER",
    },
    SUBMISSION_TYPE_FINAL_DETERMINATION: {"name": "Final determination", "key": PUBLIC_KEY, "direction": 0, "order": 35},
    SUBMISSION_TYPE_PROVISIONAL_DETERMINATION: {"name": "Provisional determination", "key": PUBLIC_KEY, "direction": 0, "order": 32},
    SUBMISSION_TYPE_VISIT_REPORT: {
        "name": "Visit Report", "key": "visitreport",
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    SUBMISSION_TYPE_APPLICATION_REPORT: {
        "name": "Application report", "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    SUBMISSION_TYPE_HEARING_NOTIFICATION: {
        "name": "Hearing notification", "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_HEARING_ARRANGEMENTS",
    },
    SUBMISSION_TYPE_RECONSIDERATION_REPORT: {"name": "Reconsideration report", "key": PUBLIC_KEY, "direction": 0, "order": 40},
    SUBMISSION_TYPE_RESPONSE_TO_THE_PROVISIONAL_DETERMINATION: {
        "name": "Response to the Provisional Determination", "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_PUBLISH_PUBLISHED",
    },
    SUBMISSION_TYPE_HEARING_REQUEST: {
        "name": "Hearing request", "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "PROV_FACTS_HEARINGS_TIMER",
    },
    SUBMISSION_TYPE_RESPONSE_TO_THE_FULL_DETERMINATION: {"name": "Response to the Full Determination", "key": AD_HOC_KEY, "direction": 1},
    SUBMISSION_TYPE_RECONSIDERATION_REQUEST: {
        "name": "Reconsideration request", "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "RECON_REQUEST_SUBMISSION_TIMER",
    },
    SUBMISSION_TYPE_AD_HOC: {"name": "Ad-hoc", "key": QUESTIONNAIRE_KEY, "direction": 2, "notify_template": "NOTIFY_AD_HOC_EMAIL"},
    SUBMISSION_TYPE_INVITE_3RD_PARTY: {"name": "Invite 3rd party", "key": "invite", "direction": 1},
    SUBMISSION_TYPE_GENERAL_PUBLICATION: {
        "name": "General publication - Other", "key": PUBLIC_KEY,
        "direction": 0,
        "order": 29,
    },
    SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION: {"name": "Statement of intended final determination", "key": PUBLIC_KEY, "direction": 0, "order": 30},
    SUBMISSION_TYPE_AUTHENTICATION_REPORT: {
        "name": "Authentication report", "key": QUESTIONNAIRE_KEY,
        "direction": 2,
        "notify_template": "NOTIFY_REPORT_ISSUED",
    },
    SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION: {
        "name": "Response to the statement of intended final determination", "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "RESPOND_SOIFD_SUBMISSION_TIMER",
    },
    SUBMISSION_TYPE_REQUEST_APPEAL: {
        "name": "Request appeal", "key": AD_HOC_KEY,
        "direction": 1,
        "time_window_key": "REQUEST_APPEAL_SUBMISSION_TIMER",
    },
    SUBMISSION_TYPE_ASSIGN_TO_CASE: {"name": "Additional User Request", "key": "assign", "direction": 1},
    SUBMISSION_TYPE_GENERAL_PUBLICATION_APPLICATION: {"name": "General publication - Application", "key": PUBLIC_KEY, "direction": 0, "order": 4,},
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTE_OF_MEETING: {"name": "General publication - Note of meeting", "key": PUBLIC_KEY, "direction": 0, "order": 5,},
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_EXTENSION: {"name": "General publication - Notice of extension", "key": PUBLIC_KEY, "direction": 0, "order": 7,},
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_PROPOSED_SAMPLE: {
        "name": "General publication - Notice of proposed sample", "key": PUBLIC_KEY,
        "direction": 0,
        "order": 9,
    },
    SUBMISSION_TYPE_GENERAL_PUBLICATION_CASE_TIMELINE: {"name": "General publication - Case timeline", "key": PUBLIC_KEY, "direction": 0, "order": 11,},
    SUBMISSION_TYPE_GENERAL_PUBLICATION_SUBMISSION_FROM_AN_INTERESTED_PARTY: {
        "name": "General publication - Submission (from an interested party)", "key": PUBLIC_KEY,
        "direction": 0,
        "order": 15,
    },
    SUBMISSION_TYPE_GENERAL_PUBLICATION_PRE_SAMPLING_QUESTIONNAIRE: {
        "name": "General publication - Pre-sampling questionnaire", "key": PUBLIC_KEY,
        "direction": 0,
        "order": 17,
    },
    SUBMISSION_TYPE_GENERAL_PUBLICATION_QUESTIONNAIRE: {"name": "General publication - Questionnaire", "key": PUBLIC_KEY, "direction": 0, "order": 19,},
    SUBMISSION_TYPE_GENERAL_PUBLICATION_VERIFICATION_REPORT: {"name": "General publication - Verification report", "key": PUBLIC_KEY, "direction": 0, "order": 21,},
    SUBMISSION_TYPE_GENERAL_PUBLICATION_FINAL_REPORTS: {"name": "General publication - Final reports", "key": PUBLIC_KEY, "direction": 0, "order": 23,},
    SUBMISSION_TYPE_GENERAL_PUBLICATION_TERMINATION_REPORTS: {"name": "General publication - Termination reports", "key": PUBLIC_KEY, "direction": 0, "order": 27,},
}

type_requires = {
    "Response to the Statement of Essential Facts": "The Statement of Essential Facts",
    "Hearing notification": "Hearing request",
    "Reconsideration report": "Reconsideration request",
    "Response to the Provisional Determination": "Provisional determination",
    "Response to the Full Determination": "Hearing request",
}


def create_update_submissiontype(apps, schema_editor):
    SubmissionType = apps.get_model('cases', 'SubmissionType')
    for key, values in submissiontype_values.items():
        SubmissionType.objects.update_or_create(id=key, defaults=values)

    for key, value in type_requires.items():
        obj_requiring = SubmissionType.objects.get(name=key)
        obj_required = SubmissionType.objects.get(name=value)
        obj_requiring.requires = obj_required
        obj_requiring.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0051_auto_20210217_1440'),
    ]

    operations = [
        migrations.RunPython(create_update_submissiontype),
    ]


