# Generated by Django 2.2.13 on 2021-02-12 07:50

from django.db import migrations, models

from cases.constants import (
    SUBMISSION_TYPE_APPLICATION,
    SUBMISSION_TYPE_QUESTIONNAIRE,
    SUBMISSION_TYPE_GENERAL,
    SUBMISSION_TYPE_EX_OFFICIO,
    SUBMISSION_TYPE_NOTICE_OF_INITIATION,
    SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE,
    SUBMISSION_TYPE_REGISTER_INTEREST,
    SUBMISSION_TYPE_STATEMENT_OF_ESSENTIAL_FACTS,
    SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_ESSENTIAL_FACTS,
    SUBMISSION_TYPE_FINAL_DETERMINATION,
    SUBMISSION_TYPE_PROVISIONAL_DETERMINATION,
    SUBMISSION_TYPE_VISIT_REPORT,
    SUBMISSION_TYPE_APPLICATION_REPORT,
    SUBMISSION_TYPE_HEARING_NOTIFICATION,
    SUBMISSION_TYPE_RECONSIDERATION_REPORT,
    SUBMISSION_TYPE_RESPONSE_TO_THE_PROVISIONAL_DETERMINATION,
    SUBMISSION_TYPE_HEARING_REQUEST,
    SUBMISSION_TYPE_RESPONSE_TO_THE_FULL_DETERMINATION,
    SUBMISSION_TYPE_RECONSIDERATION_REQUEST,
    SUBMISSION_TYPE_AD_HOC,
    SUBMISSION_TYPE_INVITE_3RD_PARTY,
    SUBMISSION_TYPE_GENERAL_PUBLICATION,
    SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
    SUBMISSION_TYPE_AUTHENTICATION_REPORT,
    SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
    SUBMISSION_TYPE_REQUEST_APPEAL,
    SUBMISSION_TYPE_ASSIGN_TO_CASE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_APPLICATION,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTE_OF_MEETING,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_EXTENSION,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_NOTICE_OF_PROPOSED_SAMPLE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_CASE_TIMELINE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_SUBMISSION_FROM_AN_INTERESTED_PARTY,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_PRE_SAMPLING_QUESTIONNAIRE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_QUESTIONNAIRE,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_VERIFICATION_REPORT,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_FINAL_REPORTS,
    SUBMISSION_TYPE_GENERAL_PUBLICATION_TERMINATION_REPORTS,
)



list = [
{
    
    "pk": 1,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION,
        "name": "Draft",
        "public_name": "Draft",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True,
        "send_confirmation_notification": ""
    }
},
{
    
    "pk": 2,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION,
        "name": "Review draft",
        "public_name": "In review",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": True,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_DRAFT_APPLICATION_RECEIVED"
    }
},
{
    
    "pk": 3,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION,
        "name": "Awaiting information",
        "public_name": "Awaiting information",
        "order": 3,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 4,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION,
        "name": "Completing",
        "public_name": "Proceed",
        "order": 4,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review_ok": True,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_DRAFT_APPLICATION_REVIEWED"
    }
},
{
    
    "pk": 5,
    "fields": {
        "type": SUBMISSION_TYPE_QUESTIONNAIRE,
        "name": "Draft",
        "public_name": "",
        "order": 1,
        "locking": False,
        "version": False,
        "duration": 37,
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 6,
    "fields": {
        "type": SUBMISSION_TYPE_QUESTIONNAIRE,
        "name": "Sent",
        "public_name": "Received",
        
        "order": 2,
        "locking": False,
        "version": False,
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 7,
    "fields": {
        "type": SUBMISSION_TYPE_QUESTIONNAIRE,
        "name": "Received",
        "public_name": "Submitted",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 8,
    "fields": {
        "type": SUBMISSION_TYPE_QUESTIONNAIRE,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 9,
    "fields": {
        "type": SUBMISSION_TYPE_QUESTIONNAIRE,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 10,
    "fields": {
        "type": SUBMISSION_TYPE_GENERAL,
        "name": "In progress",
        "public_name": "Draft",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 11,
    "fields": {
        "type": SUBMISSION_TYPE_GENERAL,
        "name": "Received",
        "public_name": "Submitted",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 12,
    "fields": {
        "type": SUBMISSION_TYPE_GENERAL,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 13,
    "fields": {
        "type": SUBMISSION_TYPE_GENERAL,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 14,
    "fields": {
        "type": SUBMISSION_TYPE_HEARING_NOTIFICATION,
        "name": "Draft",
        "public_name": "",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 15,
    "fields": {
        "type": SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE,
        "name": "Sent",
        "public_name": "Received",
        "order": 2,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 16,
    "fields": {
        "type": SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE,
        "name": "Received",
        "public_name": "Submitted",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 17,
    "fields": {
        "type": SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 18,
    "fields": {
        "type": SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE,
        "name": "Deficient",
        "public_name": "Deficient",
        
        "order": 5,
        "locking": False,
        "version": True,
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 19,
    "fields": {
        "type": SUBMISSION_TYPE_REGISTER_INTEREST,
        "name": "In progress",
        "public_name": "Draft",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 20,
    "fields": {
        "type": SUBMISSION_TYPE_REGISTER_INTEREST,
        "name": "Received",
        "public_name": "Submitted",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 21,
    "fields": {
        "type": SUBMISSION_TYPE_REGISTER_INTEREST,
        "name": "Sufficient",
        "public_name": "Accepted",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 22,
    "fields": {
        "type": SUBMISSION_TYPE_REGISTER_INTEREST,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 23,
    "fields": {
        "type": SUBMISSION_TYPE_GENERAL,
        "name": "Sent",
        "public_name": "Received",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 24,
    "fields": {
        "type": SUBMISSION_TYPE_STATEMENT_OF_ESSENTIAL_FACTS,
        "name": "Created",
        "public_name": "",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 25,
    "fields": {
        "type": SUBMISSION_TYPE_STATEMENT_OF_ESSENTIAL_FACTS,
        "name": "Published",
        "public_name": "Published",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 26,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_ESSENTIAL_FACTS,
        "name": "In progress",
        "public_name": "Draft",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 27,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_ESSENTIAL_FACTS,
        "name": "Sent",
        "public_name": "Received",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 28,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_ESSENTIAL_FACTS,
        "name": "Received",
        "public_name": "Submitted",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 29,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION,
        "name": "Received",
        "public_name": "Submitted",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_FINAL_APPLICATION_RECEIVED"
    }
},
{
    
    "pk": 30,
    "fields": {
        "type": SUBMISSION_TYPE_VISIT_REPORT,
        "name": "Received",
        "public_name": "Submitted",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 31,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_PROVISIONAL_DETERMINATION,
        "name": "In progress",
        "public_name": "Draft",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 32,
    "fields": {
        "type": SUBMISSION_TYPE_RECONSIDERATION_REPORT,
        "name": "Created",
        "public_name": "",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 33,
    "fields": {
        "type": SUBMISSION_TYPE_RECONSIDERATION_REPORT,
        "name": "Published",
        "public_name": "Published",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 34,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_APPLICATION_SUCCESSFUL"
    }
},
{
    
    "pk": 35,
    "fields": {
        "type": SUBMISSION_TYPE_FINAL_DETERMINATION,
        "name": "Published",
        "public_name": "Published",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 36,
    "fields": {
        "type": SUBMISSION_TYPE_AD_HOC,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 0,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 37,
    "fields": {
        "type": SUBMISSION_TYPE_HEARING_NOTIFICATION,
        "name": "Sent",
        "public_name": "Sent",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 38,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_PROVISIONAL_DETERMINATION,
        "name": "Received",
        "public_name": "Submitted",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 39,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_PROVISIONAL_DETERMINATION,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 40,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_PROVISIONAL_DETERMINATION,
        "name": "Deficient",
        "public_name": "Deficient",
        
        "order": 5,
        "locking": False,
        "version": True,
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 41,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_PROVISIONAL_DETERMINATION,
        "name": "Sent",
        "public_name": "Received",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 42,
    "fields": {
        "type": SUBMISSION_TYPE_RECONSIDERATION_REQUEST,
        "name": "Received",
        "public_name": "Submitted",
        "order": 1,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 43,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_FULL_DETERMINATION,
        "name": "In progress",
        "public_name": "Draft",
        "order": 3,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 44,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_ESSENTIAL_FACTS,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 45,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_ESSENTIAL_FACTS,
        "name": "Deficient",
        "public_name": "Deficient",
        
        "order": 5,
        "locking": False,
        "version": True,
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 46,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_FULL_DETERMINATION,
        "name": "Received",
        "public_name": "Submitted",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 47,
    "fields": {
        "type": SUBMISSION_TYPE_VISIT_REPORT,
        "name": "Draft",
        "public_name": "Draft",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 48,
    "fields": {
        "type": SUBMISSION_TYPE_VISIT_REPORT,
        "name": "Sent",
        "public_name": "Received",
        "order": 2,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 49,
    "fields": {
        "type": SUBMISSION_TYPE_HEARING_NOTIFICATION,
        "name": "Received",
        "public_name": "Submitted",
        "order": 0,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 50,
    "fields": {
        "type": SUBMISSION_TYPE_VISIT_REPORT,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 51,
    "fields": {
        "type": SUBMISSION_TYPE_VISIT_REPORT,
        "name": "Deficient",
        "public_name": "Deficient",
        
        "order": 5,
        "locking": False,
        "version": True,
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 52,
    "fields": {
        "type": SUBMISSION_TYPE_RECONSIDERATION_REQUEST,
        "name": "In progress",
        "public_name": "Draft",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 53,
    "fields": {
        "type": SUBMISSION_TYPE_HEARING_REQUEST,
        "name": "In progress",
        "public_name": "Draft",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 54,
    "fields": {
        "type": SUBMISSION_TYPE_HEARING_REQUEST,
        "name": "Received",
        "public_name": "Submitted",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 55,
    "fields": {
        "type": SUBMISSION_TYPE_HEARING_REQUEST,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 56,
    "fields": {
        "type": SUBMISSION_TYPE_HEARING_REQUEST,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 57,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION_REPORT,
        "name": "Draft",
        "public_name": "",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 58,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION_REPORT,
        "name": "Sent",
        "public_name": "Received",
        "order": 2,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 59,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION_REPORT,
        "name": "Received",
        "public_name": "Submitted",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 60,
    "fields": {
        "type": SUBMISSION_TYPE_AD_HOC,
        "name": "Sent",
        "public_name": "Received",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 61,
    "fields": {
        "type": SUBMISSION_TYPE_AD_HOC,
        "name": "In progress",
        "public_name": "Draft",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 62,
    "fields": {
        "type": SUBMISSION_TYPE_AD_HOC,
        "name": "Draft",
        "public_name": "",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 63,
    "fields": {
        "type": SUBMISSION_TYPE_AD_HOC,
        "name": "Received",
        "public_name": "Submitted",
        "order": 0,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 64,
    "fields": {
        "type": SUBMISSION_TYPE_QUESTIONNAIRE,
        "name": "In progress",
        "public_name": "Draft",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 65,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION_REPORT,
        "name": "In progress",
        "public_name": "Draft",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 66,
    "fields": {
        "type": SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE,
        "name": "In progress",
        "public_name": "Draft",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 67,
    "fields": {
        "type": SUBMISSION_TYPE_VISIT_REPORT,
        "name": "Draft",
        "public_name": "Draft",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 68,
    "fields": {
        "type": SUBMISSION_TYPE_HEARING_NOTIFICATION,
        "name": "In progress",
        "public_name": "Draft",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 69,
    "fields": {
        "type": SUBMISSION_TYPE_INVITE_3RD_PARTY,
        "name": "Invite draft",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 70,
    "fields": {
        "type": SUBMISSION_TYPE_INVITE_3RD_PARTY,
        "name": "Invite requested",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 71,
    "fields": {
        "type": SUBMISSION_TYPE_INVITE_3RD_PARTY,
        "name": "Invites sent",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 72,
    "fields": {
        "type": SUBMISSION_TYPE_INVITE_3RD_PARTY,
        "name": "Invites declined",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 73,
    "fields": {
        "type": SUBMISSION_TYPE_EX_OFFICIO,
        "name": "Created",
        "public_name": "Created",
        "order": 1,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": True,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 74,
    "fields": {
        "type": SUBMISSION_TYPE_NOTICE_OF_INITIATION,
        "name": "Created",
        "public_name": "",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 75,
    "fields": {
        "type": SUBMISSION_TYPE_FINAL_DETERMINATION,
        "name": "Created",
        "public_name": "",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 76,
    "fields": {
        "type": SUBMISSION_TYPE_PROVISIONAL_DETERMINATION,
        "name": "Created",
        "public_name": "",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 77,
    "fields": {
        "type": SUBMISSION_TYPE_PROVISIONAL_DETERMINATION,
        "name": "Published",
        "public_name": "Published",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 78,
    "fields": {
        "type": SUBMISSION_TYPE_PRE_SAMPLING_QUESTIONNAIRE,
        "name": "Draft",
        "public_name": "",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 79,
    "fields": {
        "type": SUBMISSION_TYPE_NOTICE_OF_INITIATION,
        "name": "Published",
        "public_name": "Published",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 80,
    "fields": {
        "type": SUBMISSION_TYPE_GENERAL_PUBLICATION,
        "name": "Created",
        "public_name": "",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{

    "pk": 81,
    "fields": {
        "type": SUBMISSION_TYPE_GENERAL_PUBLICATION,
        "name": "Published",
        "public_name": "Published",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 82,
    "fields": {
        "type": 23,
        "name": "Created",
        "public_name": "",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 83,
    "fields": {
        "type": 23,
        "name": "Published",
        "public_name": "Published",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 84,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
        "name": "In progress",
        "public_name": "Draft",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 85,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
        "name": "Sent",
        "public_name": "Received",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 86,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
        "name": "Received",
        "public_name": "Submitted",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 87,
    "fields": {
        "type": SUBMISSION_TYPE_REQUEST_APPEAL,
        "name": "In progress",
        "public_name": "Draft",
        "order": 0,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 88,
    "fields": {
        "type": SUBMISSION_TYPE_REQUEST_APPEAL,
        "name": "Received",
        "public_name": "Submitted",
        "order": 1,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 89,
    "fields": {
        "type": SUBMISSION_TYPE_AD_HOC,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 0,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 90,
    "fields": {
        "type": SUBMISSION_TYPE_RECONSIDERATION_REQUEST,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 0,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 91,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_FULL_DETERMINATION,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 0,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 92,
    "fields": {
        "type": SUBMISSION_TYPE_INVITE_3RD_PARTY,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 93,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_FULL_DETERMINATION,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 94,
    "fields": {
        "type": SUBMISSION_TYPE_RECONSIDERATION_REQUEST,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 95,
    "fields": {
        "type": SUBMISSION_TYPE_GENERAL_PUBLICATION,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 0,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 96,
    "fields": {
        "type": SUBMISSION_TYPE_GENERAL_PUBLICATION,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 97,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 0,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{   
    "pk": 98,
    "fields": {
        "type": SUBMISSION_TYPE_RESPONSE_TO_THE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{   
    "pk": 99,
    "fields": {
        "type": SUBMISSION_TYPE_REQUEST_APPEAL,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 0,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{   
    "pk": 100,
    "fields": {
        "type": SUBMISSION_TYPE_REQUEST_APPEAL,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    "pk": 101,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION_REPORT,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{   
    "pk": 102,
    "fields": {
        "type": SUBMISSION_TYPE_HEARING_NOTIFICATION,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{   
    "pk": 103,
    "fields": {
        "type": SUBMISSION_TYPE_APPLICATION_REPORT,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{   
    "pk": 104,
    "fields": {
        "type": SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
        "name": "Draft",
        "public_name": "",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 105,
    "fields": {
        "type": SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
        "name": "Sent",
        "public_name": "Received",
        
        "order": 2,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 106,
    "fields": {
        "type": SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
        "name": "Received",
        "public_name": "Submitted",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False,
        "send_confirmation_notification": "NOTIFY_SUBMISSION_RECEIVED"
    }
},
{
    
    "pk": 107,
    "fields": {
        "type": SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 108,
    "fields": {
        "type": SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
        "name": "Deficient",
        "public_name": "Deficient",
        "order": 5,
        "locking": False,
        "version": True,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 109,
    "fields": {
        "type": SUBMISSION_TYPE_STATEMENT_OF_INTENDED_FINAL_DETERMINATION,
        "name": "In progress",
        "public_name": "Draft",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 110,
    "fields": {
        "type": SUBMISSION_TYPE_HEARING_NOTIFICATION,
        "name": "Sufficient",
        "public_name": "Sufficient",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 111,
    "fields": {
        "type": SUBMISSION_TYPE_ASSIGN_TO_CASE,
        "name": "Assign draft",
        "order": 1,
        "locking": False,
        "version": False,
        
        "default": True,
        "sent": False,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": True
    }
},
{
    
    "pk": 112,
    "fields": {
        "type": SUBMISSION_TYPE_ASSIGN_TO_CASE,
        "name": "Assign requested",
        "order": 2,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": False,
        "received": True,
        "sufficient": False,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 113,
    "fields": {
        "type": SUBMISSION_TYPE_ASSIGN_TO_CASE,
        "name": "Accepted",
        "order": 3,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": True,
        "review": False,
        "draft": False
    }
},
{
    
    "pk": 114,
    "fields": {
        "type": SUBMISSION_TYPE_ASSIGN_TO_CASE,
        "name": "Assignment declined",
        "order": 4,
        "locking": True,
        "version": False,
        
        "default": False,
        "sent": True,
        "received": False,
        "sufficient": False,
        "review": False,
        "draft": False
    }
}

]

class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0052_populate_submissiontype'),
    ]

    operations = [
    ]
