# Generated by Django 3.2.12 on 2022-02-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0054_populate_submissiontype_statement_intended_preliminary_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetype',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
