# Generated by Django 3.2.12 on 2022-02-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0055_alter_casetype_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseworkflow',
            name='workflow',
            field=models.JSONField(default=dict),
        ),
    ]
