# Generated by Django 3.2.12 on 2022-02-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0056_alter_caseworkflow_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseworkflowstate',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
