# Generated by Django 3.2.12 on 2022-02-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0057_alter_caseworkflowstate_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='deficiency_notice_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='review',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
