# Generated by Django 3.2.14 on 2022-08-12 14:53

from django.db import migrations

from cases import constants

PUBLIC_KEY = "public"


def create_update_submission_types(apps, schema_editor):  # noqa
    """Create or update submission types.

    Formerly submission type initial data was loaded using json fixtures.
    This migration takes a preferred approach to load those data using
    `submission_type_values` defined in this module.
    """
    submission_type_class = apps.get_model("cases", "SubmissionType")
    submission_type_class.objects.update_or_create(
        id=constants.SUBMISSION_TYPE_LETTER_OF_AUTHORITY,
        name="Letter of Authority",
        key="public",
        defaults={
            "direction": 0,
            "order": 20
        }
    )


class Migration(migrations.Migration):
    dependencies = [
        ('cases', '0058_auto_20220207_1201'),
    ]

    operations = [
        migrations.RunPython(create_update_submission_types),
    ]
