# Generated by Django 3.2.12 on 2022-04-21 15:44

from django.db import migrations, models
import django.db.models.deletion

def populate_user_organisation_case_role(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_userorganisationcaserole'),
        ('cases', '0058_auto_20220207_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user_organisation_case_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='security.userorganisationcaserole'),
        ),
    ]
