# Generated by Django 3.2.15 on 2022-10-27 13:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0060_submission_primary_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportsource',
            name='country',
            field=django_countries.fields.CountryField(max_length=3),
        ),
    ]
