# Generated by Django 3.2.15 on 2022-10-31 11:25

from django.db import migrations


def change_safeguarding_review_name(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    CaseType = apps.get_model("cases", "CaseType")
    db_alias = schema_editor.connection.alias
    CaseType.objects.using(db_alias).filter(name="Suspension Review").update(
        name="Suspension application", acronym="SA"
    )

    CaseType.objects.using(db_alias).filter(name="Safeguard suspension review").update(
        name="Safeguard suspension application"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0061_alter_exportsource_country"),
    ]

    operations = [migrations.RunPython(change_safeguarding_review_name)]
