# Generated by Django 3.2.15 on 2022-11-28 15:19

from django.db import migrations

from cases import constants


def create_new_invitation_submission_status(apps, schema_editor):
    SubmissionStatus = apps.get_model("cases", "SubmissionStatus")
    db_alias = schema_editor.connection.alias
    latest_id = SubmissionStatus.objects.using(db_alias).last().id + 1

    SubmissionStatus.objects.using(db_alias).create(
        id=latest_id,
        type_id=constants.SUBMISSION_TYPE_INVITE_3RD_PARTY,
        name="Invite approved",
        public_name="Invite approved",
        order=6,
        review_ok=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0062_auto_20221031_1125"),
    ]

    operations = [migrations.RunPython(create_new_invitation_submission_status)]
