# Generated by Django 3.2.15 on 2022-12-14 10:55

from django.db import migrations

def alter_invite_submission_types(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    SubmissionStatus = apps.get_model("cases", "SubmissionStatus")
    db_alias = schema_editor.connection.alias



    SubmissionStatus.objects.using(db_alias).filter(
        id=69
    ).update(
        name="Draft",
        public_name="Draft",

    )


    SubmissionStatus.objects.using(db_alias).filter(
        id=70
    ).update(
        name="Waiting TRA review",
        public_name="Waiting TRA review",
        locking=True,
        version=False,
        default=False,
        sent=False,
        received=True,
        sufficient=False,
        review=False,
        draft=False,
        review_ok=False
    )

    SubmissionStatus.objects.using(db_alias).filter(
        id=92
    ).update(
        name="Deficient",
        public_name="Deficient",
        locking=False,
        version=True,
        default=False,
        sent=False,
        received=False,
        sufficient=False,
        review=False,
        draft=False,
        review_ok=False
    )

    SubmissionStatus.objects.using(db_alias).filter(
        id=72
    ).update(
        name="Invitation sent",
        public_name="Invitation sent",
        locking=True,
        version=False,
        default=False,
        sent=True,
        received=False,
        sufficient=False,
        review=False,
        draft=False,
        review_ok=False
    )

    SubmissionStatus.objects.using(db_alias).filter(
        id=71
    ).update(
        name="Waiting approval",
        public_name="Waiting TRA review",
        locking=True,
        version=False,
        default=False,
        sent=False,
        received=False,
        sufficient=True,
        review=False,
        draft=False,
        review_ok=False
    )

    SubmissionStatus.objects.using(db_alias).filter(
        id=159
    ).update(
        name="Approved",
        public_name="Approved",
        locking=True,
        version=False,
        default=False,
        sent=False,
        received=False,
        sufficient=False,
        review=False,
        draft=False,
        review_ok=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0063_auto_20221128_1519'),
    ]

    operations = [
        migrations.RunPython(alter_invite_submission_types)
    ]
