# Generated by Django 3.2.15 on 2023-06-05 13:47

from django.db import migrations


def create_bsg_casetype(apps, schema_editor):
    CaseType = apps.get_model("cases", "CaseType")
    WorkflowTemplate = apps.get_model("workflow", "WorkflowTemplate")

    try:
        workflow_object = WorkflowTemplate.objects.get(id="259838a3-21b9-4232-a134-630495e4835c")
        CaseType.objects.create(
            name="Bilateral Safeguards Review",
            acronym="BSG",
            order=160,
            internal=True,
            workflow=workflow_object,
            colour="#e69f00",
        )
    except WorkflowTemplate.DoesNotExist:
        return True


def delete_bsg_casetype(apps, schema_editor):
    CaseType = apps.get_model("cases", "CaseType")

    CaseType.objects.filter(acronym="BSG").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0066_auto_20230302_1007"),
    ]

    operations = [migrations.RunPython(create_bsg_casetype, delete_bsg_casetype)]
