# Generated by Django 2.0.13 on 2019-06-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_auto_20190520_1322"),
    ]

    operations = [
        migrations.RemoveField(model_name="contactuser", name="case",),
        migrations.RemoveField(model_name="contactuser", name="contact",),
        migrations.RemoveField(model_name="contactuser", name="created_by",),
        migrations.RemoveField(model_name="contactuser", name="modified_by",),
        migrations.RemoveField(model_name="contactuser", name="user",),
        migrations.DeleteModel(name="ContactUser",),
    ]
