version: '2'
services:
  redis:
    image: redis:alpine
    container_name: redis-test
  postgres:
    image: postgres:10.1
    container_name: postgres-test
    environment:
      POSTGRES_DB: trade_remedies
      POSTGRES_USER: uktrade
      POSTGRES_PASSWORD: uktrade
  test-trade-remedies-api:
    build: .
    env_file:
      - test.env
    depends_on:
      - postgres
      - redis
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 120s -wait tcp://redis:6379 -timeout 120s /opt/traderemedies/api/bootstrap.sh test
