version: "3"
services:
  api:
    build:
       context: . 
    ports:
      - "8000:8000"
    volumes:
      - ./trade_remedies_api:/app/
    env_file:
      - local.env
    depends_on:
      - postgres
      - redis
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=trade_remedies_api.settings.local
    networks:
      - proxynet
  celery:
    build:
       context: . 
    build: .
    command: celery -A trade_remedies_api worker -l INFO
    volumes:
      - ./trade_remedies_api:/app/
    env_file:
      - local.env
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=trade_remedies_api.settings.local
    networks:
      - proxynet
  postgres:
    image: postgres:10.7
    ports:
      - "5432:5432"
    volumes:
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: trade_remedies
      POSTGRES_USER: uktrade
      POSTGRES_PASSWORD: uktrade
    networks:
      - proxynet
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - proxynet
networks:
  proxynet:
    name: trade_remedies_network