version: "3"
services:
  api:
    build:
       context: .
    ports:
      - "8000:8000"
    volumes:
      - ./trade_remedies_api:/app/
      - ./requirements.in:/app/requirements.in/
      - ./requirements:/app/requirements/
    env_file:
      - local.env
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
  celery:
    build:
       context: .
    command: celery -A config worker -l DEBUG
    volumes:
      - ./trade_remedies_api:/app/
    env_file:
      - local.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DATABASE_URL=psql://postgres:postgres@postgres:5432/trade_remedies
  apitest:
    build:
       context: .
    ports:
      - "8003:8000"
    volumes:
      - ./trade_remedies_api:/app/
    env_file:
      - local.env
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.bdd
      - DATABASE_URL=psql://postgres:postgres@postgres:5432/trade_remedies_api_test
  postgres:
    image: postgres:10.15
    ports:
      - "5432:5432"
    volumes:
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: trade_remedies
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  opensearch:
    image: opensearchproject/opensearch:1.2.4
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
