# Generated by Django 2.2.6 on 2020-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_userprofile_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verify_code_last_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
