# Generated by Django 2.0.1 on 2019-02-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_auto_20181211_1642"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="tra_organisation",
            field=models.BooleanField(default=False),
        ),
    ]
