# Generated by Django 2.0.1 on 2019-02-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0005_auto_20190219_1045"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisation", old_name="tra_organisation", new_name="gov_body",
        ),
    ]
