# Generated by Django 2.2.4 on 2019-08-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0007_auto_20190402_1559"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation", name="fraudulent", field=models.BooleanField(default=False),
        ),
    ]
