# Generated by Django 2.2.5 on 2019-11-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0010_auto_20191024_1353"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="merged_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_from_org",
                to="organisations.Organisation",
            ),
        ),
    ]
