# Generated by Django 2.2.6 on 2019-11-19 12:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0011_organisation_merged_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="json_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
