# Generated by Django 3.2.12 on 2022-02-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_organisation_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
