# Generated by Django 3.2.15 on 2022-09-23 15:42

from django.contrib.postgres.operations import TrigramExtension

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_alter_organisation_json_data'),
    ]

    operations = [
        TrigramExtension(),
    ]
