# Generated by Django 3.2.15 on 2022-12-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0014_alter_organisation_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="draft",
            field=models.BooleanField(default=False),
        ),
    ]
