# Generated by Django 3.2.15 on 2022-12-05 14:31

import audit.mixins
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0014_alter_organisation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='merged_from_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from_child_org', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='merged_from_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from_parent_org', to='organisations.organisation'),
        ),
        migrations.CreateModel(
            name='OrganisationMerge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('child_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organisation_merged_into', to='organisations.organisation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisationmerge_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisationmerge_modified_by', to=settings.AUTH_USER_MODEL)),
                ('parent_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organisation_merged_children', to='organisations.organisation')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin, audit.mixins.AuditableMixin),
        ),
    ]
