# Generated by Django 3.2.15 on 2022-12-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0015_auto_20221205_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='merged_from_child',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='merged_from_parent',
        ),
    ]
