# Generated by Django 3.2.15 on 2023-01-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0016_duplicateorganisationmerge_organisationmergerecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="duplicateorganisationmerge",
            name="parent_organisation",
        ),
        migrations.AddField(
            model_name="organisationmergerecord",
            name="parent_organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merge_records",
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="organisationmergerecord",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Not started"),
                    (2, "No duplicates found"),
                    (2, "Started"),
                    (3, "Complete"),
                ],
                default=1,
            ),
        ),
    ]
