# Generated by Django 3.2.15 on 2023-01-23 14:24

import audit.mixins
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0065_auto_20221214_1203"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0016_duplicateorganisationmerge_organisationmergerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationmergerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_checked", "Not checked"),
                    ("no_duplicates_found", "No duplicates found"),
                    ("duplicates_found", "Duplicates found"),
                ],
                default="not_checked",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="SubmissionOrganisationMergeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                        ],
                        default="not_started",
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissionorganisationmergerecord_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissionorganisationmergerecord_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation_merge_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.organisationmergerecord",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.submission"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                dirtyfields.dirtyfields.DirtyFieldsMixin,
                audit.mixins.AuditableMixin,
            ),
        ),
        migrations.AddField(
            model_name="organisationmergerecord",
            name="submission",
            field=models.ManyToManyField(
                related_name="merge_records",
                through="organisations.SubmissionOrganisationMergeRecord",
                to="cases.Submission",
            ),
        ),
    ]
