# Generated by Django 3.2.15 on 2023-01-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0065_auto_20221214_1203"),
        ("organisations", "0020_organisationmergerecord_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionorganisationmergerecord",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="cases.submission",
            ),
        ),
    ]
