# Generated by Django 3.2.15 on 2023-03-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0021_alter_submissionorganisationmergerecord_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmergerecord',
            name='last_searched',
            field=models.DateTimeField(null=True),
        ),
    ]
