# Generated by Django 3.2.15 on 2023-03-23 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0022_organisationmergerecord_last_searched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duplicateorganisationmerge",
            name="child_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="duplicateorganisationmerge",
            name="parent_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500), blank=True, null=True, size=None
            ),
        ),
    ]
