# Generated by Django 3.2.15 on 2023-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0023_auto_20230323_1609"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationmergerecord",
            name="chosen_case_roles",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
