# Generated by Django 3.2.15 on 2023-06-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0024_organisationmergerecord_chosen_case_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationmergerecord',
            name='status',
            field=models.CharField(choices=[('not_checked', 'Not checked'), ('no_duplicates_found', 'No duplicates found'), ('duplicates_found', 'Duplicates found'), ('duplicates_resolved', 'Duplicates resolved')], default='not_checked', max_length=30),
        ),
    ]
