# Generated by Django 3.2.15 on 2023-06-07 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0067_auto_20230605_1447'),
        ('organisations', '0025_alter_organisationmergerecord_status'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE organisations_submissionorganisationmergerecord DROP CONSTRAINT organisations_submissionorganisationmergerecord_pkey"),
        migrations.AlterField(
            model_name='submissionorganisationmergerecord',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='cases.submission'),
        ),
    ]
