# Generated by Django 3.2.15 on 2023-06-07 14:11

from django.db import migrations

def add_ids(apps, schema_editor):
    import uuid
    SubmissionOrganisationMergeRecord = apps.get_model("organisations", "SubmissionOrganisationMergeRecord")
    for somr in SubmissionOrganisationMergeRecord.objects.all():
        somr.new_id = uuid.uuid4()
        somr.save()

class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0027_auto_20230607_1510'),
    ]

    operations = [
        migrations.RunPython(add_ids, migrations.RunPython.noop)
    ]
