# Generated by Django 3.2.15 on 2023-06-07 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0028_auto_20230607_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionorganisationmergerecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='submissionorganisationmergerecord',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
