# Generated by Django 2.0.1 on 2018-12-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from core.models import User


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=16, null=True)),
                ("last_validated", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
