# Generated by Django 2.0.1 on 2019-01-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_passwordresetrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verify_code",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
