# Generated by Django 2.0.1 on 2019-01-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20190109_1648"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="country",),
        migrations.RemoveField(model_name="userprofile", name="phone",),
    ]
