# Generated by Django 2.0.1 on 2019-01-21 14:30

from django.db import migrations
from django.db.models import F, Func
from core.models import User


def lower_case_emails(apps, schema_editor):
    User.objects.all().update(email=Func(F("email"), function="LOWER"))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20190116_1535"),
    ]

    operations = [
        # migrations.RunPython(lower_case_emails),
    ]
