# Generated by Django 2.0.1 on 2019-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20190121_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="twofactorauth",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
