# Generated by Django 2.0.1 on 2019-01-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_twofactorauth_locked_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="twofactorauth", name="attempts", field=models.SmallIntegerField(default=0),
        ),
    ]
