# Generated by Django 2.0.1 on 2019-02-09 19:15

from django.db import migrations, models
from django.db.models import F
from core.models import User


def user_names(apps, schema_editor):
    users = User.objects.all()
    for user in users:
        user._disable_audit = True
        user.name = f"{user.first_name} {user.last_name}".strip()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_twofactorauth_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        # migrations.RunPython(user_names),
    ]
