# Generated by Django 2.0.1 on 2019-02-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20190220_1623"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="job_role", new_name="job_title",
        ),
    ]
