# Generated by Django 2.0.1 on 2019-02-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20190227_1411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="userprofile",
                to="contacts.Contact",
            ),
        ),
    ]
