# Generated by Django 2.0.13 on 2019-03-26 13:50

from django.db import migrations
from trade_remedies_api.migrations import LoadExtension


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20190227_1606"),
    ]

    operations = [
        #        LoadExtension('pg_trgm')
    ]
