# Generated by Django 2.0.13 on 2019-06-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20190326_1350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemparameter",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("str", "String"),
                    ("list", "List"),
                    ("dict", "Dictionary"),
                    ("int", "Number"),
                    ("bool", "Boolean"),
                ],
                default="str",
                max_length=20,
            ),
        ),
    ]
