# Generated by Django 2.0.13 on 2019-06-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_auto_20190617_0850"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": (("change_org_user", "Can modify own organisation users"),)},
        ),
    ]
