# Generated by Django 2.0.13 on 2019-07-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20190617_1426"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("change_org_user", "Can modify own organisation users"),
                    ("can_view_all_org_cases", "Can view all cases across the Organisation"),
                )
            },
        ),
    ]
