# Generated by Django 2.0.13 on 2019-08-04 22:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_auto_20190713_0832"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="settings",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
