# Generated by Django 2.2.4 on 2019-09-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_userprofile_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemparameter", name="editable", field=models.BooleanField(default=False),
        ),
    ]
