# Generated by Django 2.2.20 on 2021-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_twofactorauth_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='delivery_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=8),
        ),
    ]
