# Generated by Django 3.2.12 on 2022-02-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_twofactorauth_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemparameter',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
