# Generated by Django 2.2.27 on 2022-02-11 10:03

from django.db import migrations


def invalidate_existing_reset_requests(apps, schema_editor):
    from django.utils import timezone
    PasswordResetRequest = apps.get_model("core", "PasswordResetRequest")
    db_alias = schema_editor.connection.alias

    for password_reset_request in PasswordResetRequest.objects.using(db_alias).all():
        password_reset_request.invalidated_at = timezone.now()
        password_reset_request.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_twofactorauth_delivery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetrequest',
            old_name='code',
            new_name='token',
        ),
        migrations.RunPython(invalidate_existing_reset_requests)
    ]
