# Generated by Django 3.2.12 on 2022-04-21 12:35

from django.db import migrations, models
import django.db.models.deletion

def migrate_user_profile_information(apps, schema_editor):
    User = apps.get_model("core", "User")
    UserProfile = apps.get_model("core", "UserProfile")

    for user in User.objects.all():
        try:
            if user_profile := user.userprofile:
                user._disable_audit = True
                user.job_title = user_profile.job_title
                user.email_verified_at = user_profile.email_verified_at
                user.email_verify_code = user_profile.email_verify_code
                user.email_verify_code_last_sent = user_profile.email_verify_code_last_sent
                user.settings = user_profile.settings
                user.settings = user_profile.settings
                user.save()
                print(f"UserProfile successfully copied for {user.email}")
        except UserProfile.DoesNotExist:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220211_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verify_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verify_code_last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='core.jobtitle'),
        ),
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.RunPython(migrate_user_profile_information),
        migrations.RemoveField(
            model_name='user',
            name='auto_assign',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_code_created_at',
        ),
    ]
