# Generated by Django 3.2.13 on 2022-05-27 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220211_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
