# Generated by Django 3.2.14 on 2022-08-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_passwordresetrequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
