# Generated by Django 3.2.15 on 2022-10-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
