# Generated by Django 3.2.15 on 2022-10-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="user",
        ),
        migrations.AddField(
            model_name="feedback",
            name="logged_in",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
