# Generated by Django 3.2.15 on 2022-10-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_auto_20221031_1550"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="what_didnt_work_so_well",
        ),
    ]
