# Generated by Django 3.2.15 on 2022-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_feedback_what_didnt_work_so_well'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='form_placement',
            field=models.PositiveSmallIntegerField(choices=[(1, 'banner'), (2, 'footer')], null=True),
        ),
    ]
