STATE_UNKONWN = "UNKNOWN"
STATE_INCOMPLETE = "INCOMPLETE"
STATE_INPROGRESS = "INPROGRESS"
STATE_COMPLETE = "COMPLETE"

SUBMISSION_TYPE_APPLICATION = 1
SUBMISSION_TYPE_QUESTIONNAIRE = 2
SUBMISSION_TYPE_ADHOC = 3
SUBMISSION_TYPE_EXOFFICIO = 4


SUBMISSION_APPLICATION_TYPES = [
    SUBMISSION_TYPE_APPLICATION,
    SUBMISSION_TYPE_EXOFFICIO,
]
