# Generated by Django 2.0.1 on 2019-02-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_auto_20181211_1642"),
        ("cases", "0023_remove_submission_deficiency_document"),
        ("contacts", "0003_casecontact_organisation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="casecontact", unique_together={("case", "contact", "organisation")},
        ),
    ]
