# Generated by Django 2.2.24 on 2021-10-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20190617_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='e_additional_invite_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
