# Generated by Django 2.2.24 on 2021-10-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_e_additional_invite_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='e_additional_invite_information',
            field=models.TextField(default=''),
        ),
    ]
