# Generated by Django 3.2.15 on 2023-03-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0007_contact_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="post_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
