# Generated by Django 2.0.1 on 2018-11-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_auto_20181109_1151"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionstatus",
            name="public_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
