# Generated by Django 2.0.1 on 2018-11-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_submissionstatus_public_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="response_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="deficiency_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deficiency_document",
                to="documents.Document",
            ),
        ),
    ]
