# Generated by Django 2.0.1 on 2018-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_casetype_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestage", name="flow_restrict", field=models.BooleanField(default=False),
        ),
    ]
