# Generated by Django 2.0.1 on 2019-01-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0015_casestage_flow_restrict"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="initiated_sequence",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
