# Generated by Django 2.0.1 on 2019-01-03 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_auto_20181230_1748"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="sent_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_sent_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
