# Generated by Django 2.0.13 on 2019-03-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0029_auto_20190227_1411"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissiontype", name="order", field=models.SmallIntegerField(default=0),
        ),
    ]
