# Generated by Django 2.0.13 on 2019-04-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0032_auto_20190328_1642"),
    ]

    operations = [
        migrations.AddField(
            model_name="casetype", name="order", field=models.SmallIntegerField(default=0),
        ),
    ]
