# Generated by Django 2.0.13 on 2019-04-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0034_casetype_internal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={
                "permissions": (
                    ("create_ex_oficio", "Can create an ex-oficio case"),
                    (
                        "complete_decision_tasks",
                        "Can complete decision tasks like initiation decision, final determination etc.",
                    ),
                    ("can_assign_team", "Can assign manager and team to the case"),
                    (
                        "issue_submission_requests",
                        "Can issue submission requests (questionnaires, visit report etc.)",
                    ),
                    ("workflow_editor", "Can access the workflow editor"),
                    ("can_generate_audit", "Can generate full audit trail"),
                )
            },
        ),
    ]
