# Generated by Django 2.0.13 on 2019-05-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0035_auto_20190429_1533"),
    ]

    operations = [
        migrations.RemoveField(model_name="casedocument", name="case",),
        migrations.RemoveField(model_name="casedocument", name="case_type",),
        migrations.RemoveField(model_name="casedocument", name="created_by",),
        migrations.RemoveField(model_name="casedocument", name="document",),
        migrations.RemoveField(model_name="casedocument", name="modified_by",),
        migrations.RemoveField(model_name="casedocument", name="type",),
        migrations.DeleteModel(name="CaseDocument",),
        migrations.DeleteModel(name="CaseDocumentType",),
    ]
