# Generated by Django 2.2.5 on 2019-12-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0043_case_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casemilestone", name="date", field=models.DateField(blank=True, null=True),
        ),
    ]
