# Generated by Django 2.2.5 on 2020-01-07 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0045_auto_20191216_1525"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("reference", models.CharField(max_length=30)),
                ("terminated_at", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
