# Generated by Django 2.0.1 on 2018-12-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_auto_20181015_1444"),
    ]

    operations = [
        migrations.RenameField(model_name="audit", old_name="case", new_name="case_temp",),
        migrations.AlterField(
            model_name="audit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="model_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
