# Generated by Django 2.0.1 on 2018-12-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auto_20181213_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="case_id_new",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
