# Generated by Django 2.0.1 on 2018-12-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_auto_20181213_1606"),
    ]

    operations = [
        migrations.RenameField(model_name="audit", old_name="case_id_new", new_name="case_id",),
        migrations.RemoveField(model_name="audit", name="case_temp",),
    ]
