# Generated by Django 2.2.5 on 2020-02-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0007_auto_20200203_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="audit.Audit"
            ),
        ),
    ]
