# Generated by Django 3.2.12 on 2022-02-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_precompute_case_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
