# Generated by Django 3.2.14 on 2022-08-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_auto_20220809_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
