# Generated by Django 3.2.15 on 2023-03-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0016_alter_audit_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="type",
            field=models.CharField(
                choices=[
                    ("UPDATE", "Update"),
                    ("CREATE", "Create"),
                    ("DELETE", "Delete"),
                    ("PURGE", "Purge"),
                    ("RESTORE", "Restore"),
                    ("READ", "Read"),
                    ("LOGIN", "Log In"),
                    ("LOGIN_FAILED", "Log In Failed"),
                    ("LOGOUT", "Log Out"),
                    ("EVENT", "Event"),
                    ("ATTACH", "Attach"),
                    ("NOTIFY", "Notify"),
                    ("DELIVERED", "Delivery"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PASSWORD_RESET_FAILED", "Password Reset Failed"),
                    ("USER_CREATED", "New User Created"),
                    ("EMAIL_VERIFIED", "Email Verified"),
                    ("ORGANISATION_MERGED", "Organisation Merged"),
                ],
                max_length=50,
            ),
        ),
    ]
