version: 2.1
jobs:
  code_quality:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install Python deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          name: Run black
          command: |
            . venv/bin/activate
            # black trade_remedies_api --check
      - run:
          name: Run Flake8
          command: |
            . venv/bin/activate
            pflake8 trade_remedies_api --config trade_remedies_api/pyproject.toml
  test:
    docker:
      - image: cimg/python:3.9.5
        environment:
          DATABASE_URL: psql://ubuntu@localhost:5432/trade_remedies
          DJANGO_SETTINGS_MODULE: config.settings.test
          DJANGO_SECRET_KEY: ci_only
          ALLOWED_HOSTS: "*"
          OPENSEARCH_HOST: "opensearch"
          OPENSEARCH_PORT: "9200"
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: trade_remedies
          POSTGRES_PASSWORD: ""
      - image: opensearchproject/opensearch:1.2.4
        environment:
          - discovery.type=single-node
          - plugins.security.disabled=true
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install Python deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd trade_remedies_api
            pytest --ignore=staticfiles -n 4 -m "not version2"
  collect-send-metrics:
    steps:
      - checkout
      - run:
          name: Install Python deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements/dev.txt
workflows:
  version: 2
  run_tests:
    jobs:
      - code_quality
      - test
