version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.10
        environment:
          DATABASE_URL: psql://ubuntu@localhost:5432/trade_remedies
          DJANGO_SETTINGS_MODULE: trade_remedies_api.settings.test
          SECRET_KEY: used_for_testing
          ALLOWED_HOSTS: "*"
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: trade_remedies
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install Python deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          name: Collect static
          command: |
            . venv/bin/activate
            python trade_remedies_api/manage.py collectstatic --noinput
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python trade_remedies_api/manage.py test
      - run:
          name: Run Flake8
          command: |
            . venv/bin/activate
            python -m flake8 trade_remedies_api