version: 2.1

commands:
  install_dependencies:
    description: "Install Python dependencies"
    steps:
      - run:
         name: Install Python dependencies
         command: |
            python3 -m venv venv
            echo ". venv/bin/activate" >> $BASH_ENV
            . venv/bin/activate
            pip install --upgrade pip
            pip install poetry==1.6.1
            poetry export --with dev --without-hashes -f requirements.txt -o requirements-dev.txt
            pip install -r requirements-dev.txt

  restore_dependency_cache:
    description: "Restore dependency cache."
    steps:
      - restore_cache:
          keys: 
            - deps2-{{ .Branch }}-
            - deps2-

  save_dependency_cache:
    description: "Save dependency cache."
    steps:
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "venv"

jobs:
  code_quality:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      - restore_dependency_cache
      - install_dependencies
      - save_dependency_cache
      - run:
          name: Run black
          command: |
            black trade_remedies_api --check
      - run:
          name: Run Flake8
          command: |
            pflake8 trade_remedies_api --config pyproject.toml
  test_and_fitness_functions:
    docker:
      - image: cimg/python:3.9.5
        environment:
          DATABASE_URL: psql://ubuntu@localhost:5432/trade_remedies
          DJANGO_SETTINGS_MODULE: config.settings.test
          DJANGO_SECRET_KEY: ci_only
          ALLOWED_HOSTS: "*"
          OPENSEARCH_HOST: "opensearch"
          OPENSEARCH_PORT: "9200"
      - image: cimg/postgres:12.17
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: trade_remedies
          POSTGRES_PASSWORD: ""
      - image: opensearchproject/opensearch:1.2.4
        environment:
          - discovery.type=single-node
          - plugins.security.disabled=true
    steps:
      - add_ssh_keys:
            fingerprints:
              - "9f:19:e2:26:c4:aa:6e:4d:98:77:22:09:b9:cf:50:f3"
      - checkout
      - restore_dependency_cache
      - install_dependencies
      - save_dependency_cache
      - run:
          name: Run tests and save coverage report
          command: |
            pytest trade_remedies_api
            coverage json
      - run:
          name: Send coverage report to codecov.io
          command: codecov
workflows:
  version: 2
  build:
    jobs:
      - code_quality
      - test_and_fitness_functions
