CONTRIBUTOR_ORG_CASE_ROLE = ("product_user", "contributor")
APPLICANT_ORG_CASE_ROLE = "applicant"
AWAITING_ORG_CASE_ROLE = "awaiting_approval"
REJECTED_ORG_CASE_ROLE = "rejected"
PREPARING_ORG_CASE_ROLE = "preparing"
NOT_IN_CASE_ORG_CASE_ROLES = (
    AWAITING_ORG_CASE_ROLE,
    REJECTED_ORG_CASE_ROLE,
    PREPARING_ORG_CASE_ROLE,
)
