# Generated by Django 2.0.1 on 2018-10-15 14:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("label", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("order", models.SmallIntegerField(default=0)),
                ("required", models.BooleanField(default=False)),
                ("time_gate", models.SmallIntegerField(blank=True, null=True)),
                (
                    "outcome_spec",
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NodeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ResponseType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("locked", models.BooleanField(default=False)),
                ("template", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name="node",
            name="node_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="workflow.NodeType"
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workflow.Node",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="response_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workflow.ResponseType",
            ),
        ),
    ]
