# Generated by Django 2.0.1 on 2019-02-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="node", name="node_type",),
        migrations.RemoveField(model_name="node", name="parent",),
        migrations.RemoveField(model_name="node", name="response_type",),
        migrations.DeleteModel(name="Node",),
        migrations.DeleteModel(name="NodeType",),
        migrations.DeleteModel(name="ResponseType",),
    ]
