# Generated by Django 3.2.12 on 2022-02-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190227_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtemplate',
            name='template',
            field=models.JSONField(),
        ),
    ]
