# Generated by Django 2.0.1 on 2019-03-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_auto_20181106_1037"),
    ]

    operations = [
        migrations.AddField(
            model_name="caserole", name="allow_cw_create", field=models.BooleanField(default=True),
        ),
    ]
