# Generated by Django 2.0.13 on 2019-08-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_auto_20190617_0850"),
        ("security", "0003_caserole_allow_cw_create"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercase",
            name="auth_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loa_contact",
                to="contacts.Contact",
            ),
        ),
    ]
