# Generated by Django 2.2.4 on 2019-09-01 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("security", "0004_usercase_auth_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationcaserole",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationcaserole",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="validated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
