# Generated by Django 2.2.5 on 2019-11-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_auto_20190617_0850"),
        ("security", "0006_auto_20190918_1254"),
    ]

    operations = [
        migrations.RemoveField(model_name="usercase", name="auth_contact",),
        migrations.AddField(
            model_name="organisationcaserole",
            name="auth_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loa_contact",
                to="contacts.Contact",
            ),
        ),
    ]
