# Generated by Django 3.2.13 on 2022-05-30 14:17

from django.db import migrations

import pytest


def multiply_order_by_10(apps, schema_editor):
    CaseRole = apps.get_model("security", "CaseRole")

    for case_role in CaseRole.objects.all():
        case_role.order *= 10
        case_role.save()


@pytest.mark.django_db(transaction=True)
def add_case_role(apps, schema_editor):
    CaseRole = apps.get_model("security", "CaseRole")
    new_case_role = CaseRole.objects.create(
        name="Overseas Producer",
        plural="Overseas Producers",
        key="overseas_producer",
        order=45
        )

    # get case actions and add to case role
    CaseAction = apps.get_model("security", "CaseAction")
    view_case = CaseAction.objects.get(id="VIEW_CASE")
    view_application = CaseAction.objects.get(id="VIEW_APPLICATION")
    
    new_case_role.actions.add(view_application, view_case)


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_auto_20191104_1337'),
    ]

    operations = [
        migrations.RunPython(multiply_order_by_10),
        migrations.RunPython(add_case_role),
    ]
