# Generated by Django 3.2.12 on 2022-04-21 13:03

import audit.mixins
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0007_auto_20191104_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganisationCaseRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userorganisationcaserole_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userorganisationcaserole_modified_by', to=settings.AUTH_USER_MODEL)),
                ('organisation_case_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_org_case_roles', to='security.organisationcaserole')),
                ('representing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representing_user_org_case_roles', to='security.organisationcaserole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_org_case_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin, audit.mixins.AuditableMixin),
        ),
    ]
