# Generated by Django 3.2.15 on 2023-03-23 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0007_auto_20191104_1337"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organisationcaserole",
            unique_together=set(),
        ),
    ]
