# Generated by Django 2.0.13 on 2019-04-24 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0003_auto_20190409_0826"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentbundle",
            name="finalised_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="documentbundle",
            name="finalised_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finalised_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
