# Generated by Django 2.0.13 on 2019-07-03 10:02

from django.db import migrations, models
import documents.fields


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_auto_20190502_0912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="checksum",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=documents.fields.S3FileField(max_length=1000, upload_to=""),
        ),
    ]
