# Generated by Django 2.2.6 on 2020-03-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_auto_20190703_1002"),
    ]

    operations = [
        migrations.AddField(
            model_name="document", name="indexed", field=models.NullBooleanField(),
        ),
    ]
