# Generated by Django 2.2.6 on 2020-03-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_document_indexed"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="index_state",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Unkown type)"),
                    (2, "Index failed"),
                    (3, "Full index"),
                ],
                default=0,
            ),
        ),
    ]
