# Generated by Django 2.2.6 on 2020-07-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_document_index_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="block_from_public_file",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="block_reason",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
