# Generated by Django 2.2.13 on 2021-03-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_auto_20200730_1158"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="av_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
