# Generated by Django 2.2.13 on 2021-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_document_av_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="indexed",
        ),
        migrations.AlterField(
            model_name="document",
            name="index_state",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Unknown type"),
                    (2, "Index failed"),
                    (3, "Full index"),
                ],
                default=0,
            ),
        ),
    ]
