# Generated by Django 2.2.24 on 2021-10-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20210324_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='av_reason',
        ),
        migrations.RemoveField(
            model_name='document',
            name='safe',
        ),
        migrations.RemoveField(
            model_name='document',
            name='virus_scanned_at',
        ),
    ]
