# Generated by Django 2.0.1 on 2018-10-15 14:44

import audit.models
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0002_auto_20181015_1444"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ("short_code", models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ("email_sent", models.NullBooleanField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="cases.Case"),
                ),
            ],
            options={"abstract": False,},
            bases=(
                models.Model,
                dirtyfields.dirtyfields.DirtyFieldsMixin,
                audit.mixins.AuditableMixin,
            ),
        ),
    ]
