# Generated by Django 2.0.1 on 2018-10-15 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invitations", "0001_initial"),
        ("organisations", "0001_initial"),
        ("auth", "0009_alter_user_last_name_max_length"),
        ("contacts", "0002_auto_20181015_1444"),
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="case_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="security.CaseRole"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contacts.Contact",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitation_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitation_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.Organisation",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="organisation_security_group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="auth.Group"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
