# Generated by Django 2.0.1 on 2018-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0003_invitation_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
