# Generated by Django 2.0.1 on 2018-11-26 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invitations", "0005_auto_20181106_1306"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
