# Generated by Django 2.0.13 on 2019-05-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0006_invitation_approved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="case",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="cases.Case"
            ),
        ),
    ]
