# Generated by Django 2.0.13 on 2019-05-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0008_invitation_invalid"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
