# Generated by Django 2.0.13 on 2019-05-31 09:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0009_invitation_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
