# Generated by Django 2.2.20 on 2021-07-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0010_invitation_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='cases.Submission'),
        ),
    ]
