# Generated by Django 3.2.12 on 2022-02-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0011_auto_20210709_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email_sent',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
