# Generated by Django 3.2.14 on 2022-08-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0012_auto_20220207_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
