# Generated by Django 3.2.14 on 2022-09-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0059_auto_20220812_1553'),
        ('invitations', '0015_invitation_invited_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='cases_to_link',
            field=models.ManyToManyField(related_name='cases_to_link', to='cases.Case'),
        ),
    ]
