# Generated by Django 3.2.14 on 2022-09-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0060_submission_primary_contact'),
        ('invitations', '0016_invitation_cases_to_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='cases_to_link',
            field=models.ManyToManyField(blank=True, related_name='cases_to_link', to='cases.Case'),
        ),
    ]
