# Generated by Django 3.2.15 on 2022-12-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0018_invitation_user_cases_to_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="invitation_type",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Own Organisation"), (2, "Representative"), (3, "Caseworker")],
                null=True,
            ),
        ),
    ]
