# Generated by Django 3.2.15 on 2022-12-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0020_invitation_rejected_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
