# Generated by Django 3.2.15 on 2023-02-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0023_invitation_organisation_details_captured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='organisation_details_captured',
            new_name='organisation_details_not_captured',
        ),
    ]
