# Generated by Django 2.2.6 on 2020-03-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_reference"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="estimated_duration",),
        migrations.AlterField(
            model_name="task", name="reference", field=models.IntegerField(blank=True, null=True),
        ),
    ]
