# Generated by Django 2.2.6 on 2020-04-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_auto_20200318_1335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="due_date", field=models.DateField(null=True),
        ),
    ]
