# Generated by Django 3.2.12 on 2022-02-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200420_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
