# Generated by Django 2.0.1 on 2018-10-15 14:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("UPDATE", "Update"),
                            ("CREATE", "Create"),
                            ("DELETE", "Delete"),
                            ("PURGE", "Purge"),
                            ("RESTORE", "Restore"),
                            ("READ", "Read"),
                            ("LOGIN", "Log In"),
                            ("LOGOUT", "Log Out"),
                            ("EVENT", "Event"),
                            ("ATTACH", "Attach"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model_id", models.UUIDField(blank=True, null=True)),
                ("milestone", models.BooleanField(default=False)),
                ("data", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
