# Generated by Django 2.2.6 on 2020-02-04 12:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_auto_20200128_1203"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
