# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python. Multiline strings are treated as
# verbose regular expressions by Black. Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 100
diff = true
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.venv
  | _build
  | .venv
  | tests-reports
)/
'''

# see https://pycqa.github.io/isort/docs/configuration/black_compatibility/
[tool.isort]
profile = "black"
line_length = 100
include_trailing_comma = true
multi_line_output = 3

[tool.flake8]
max-line-length = 100
extend-exclude = '''
/(
  */migrations/*.py
)/
'''
