# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python. Multiline strings are treated as
# verbose regular expressions by Black. Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 100
#diff = true
#check = true
target-versions = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.venv
  | _build
  | .venv
  | tests-reports
  | tests
  | migrations
)/
'''

# see https://pycqa.github.io/isort/docs/configuration/black_compatibility/
[tool.isort]
profile = "black"
line_length = 100
include_trailing_comma = true
multi_line_output = 3

[tool.flake8]
max-line-length = 100
per-file-ignores = '__init__.py: F401'
ignore = '''
/(
    C901
    | D100
    | D104
    | D106
    | D200
    | D203
    | D205
    | D400
    | D401
    | W503
    | W504
    | E704
    | E231
    | F841
    | F401
    | F405
    | F811
    | E722
    | E203
    | E501
'''
max-complexity = 10
application-import-names = '''
/(
    audit
    | cases
    | contacts
    | content
    | core
    | documents
    | features
    | invitations
    | notes
    | organisations
    | reports
    | security
    | tasks
    | config
    | workflow
)/
'''
import_order_style = 'smarkets'
extend-exclude = '''
/(
  */migrations/*.py
)/
'''
