# Generated by Django 2.0.1 on 2018-12-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_organisation_duplicate_of"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="organisation", unique_together=set(),),
    ]
