# Generated by Django 2.0.13 on 2019-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0006_auto_20190219_1320"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="duns_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="eori_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="organisation_website",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="vat_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
