# Generated by Django 2.0.13 on 2019-05-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0007_auto_20190521_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation", name="invalid", field=models.BooleanField(default=False),
        ),
    ]
