# Generated by Django 2.2.24 on 2021-12-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twofactorauth',
            old_name='locked_at',
            new_name='locked_until',
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
